In [1]:
import polars as pl

# infer_schema_length=None scans the WHOLE file to find the correct number of columns
df = pl.read_excel("../../data/l3-transcript-data.xlsx")
print(df.head())

Could not determine dtype for column 10, falling back to string
Could not determine dtype for column 11, falling back to string
Could not determine dtype for column 12, falling back to string

shape: (5, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ uni_code ┆ uni_name  ┆ uni_web_l ┆ major_cod ┆ … ┆ tuition_f ┆ study_pro ┆ admission ┆ admission │
│ ---      ┆ ---       ┆ ink       ┆ e         ┆   ┆ ee        ┆ gram      ┆ _type     ┆ _type_nam │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ e         │
│          ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140231V  ┆ … ┆ 30000000  ┆ null      ┆ null      ┆ null      │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140246V  ┆ … ┆ 30000000  ┆ null      ┆ null      ┆ null      │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210403V  ┆ … ┆ 30000000  ┆ null      ┆ null      ┆ null      │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210404V  ┆ … ┆ 30000000  ┆ null      ┆ null      ┆ null      │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7220201BP ┆ … ┆ 30000000  ┆ null      ┆ null      ┆ null      │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆           │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [2]:
df = df.with_columns(
    pl.when(pl.col("major_code").str.contains("V"))
    .then(pl.lit("Đại trà"))
    .when(pl.col("major_code").str.contains("BP"))
    .then(pl.lit("Đào tạo tại Bình Phước"))
    .when(pl.col("major_code").str.contains("A"))
    .then(pl.lit("Đào tạo bằng tiếng Anh"))
    .when(pl.col("major_code").str.contains("N"))
    .then(pl.lit("Đào tạo bằng tiếng Nhật"))
    .when(pl.col("major_code").str.contains("DD"))
    .then(pl.lit("Thuộc ngành Công nghệ thực phẩm (đào tạo bằng tiếng Việt)"))
    .otherwise(pl.lit(None))
    .alias("study_program")
)

In [3]:
df = df.with_columns(
    pl.lit("Học Bạ").alias("admission_type"),
    pl.lit("Sử dụng phương thức xét tuyển học bạ").alias("admission_type_name")
)

In [4]:
df

shape: (150, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ uni_code ┆ uni_name  ┆ uni_web_l ┆ major_cod ┆ … ┆ tuition_f ┆ study_pro ┆ admission ┆ admission │
│ ---      ┆ ---       ┆ ink       ┆ e         ┆   ┆ ee        ┆ gram      ┆ _type     ┆ _type_nam │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ e         │
│          ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140231V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140246V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210403V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210404V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7220201BP ┆ … ┆ 30000000  ┆ Đào tạo   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆ tại Bình  ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆ Phước     ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ QSB      ┆ null      ┆ null      ┆ 308       ┆ … ┆ 40000000  ┆ null      ┆ Học Bạ    ┆ Sử dụng   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ QSB      ┆ null      ┆ null      ┆ 146       ┆ … ┆ 30000000  ┆ null      ┆ Học Bạ    ┆ Sử dụng   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ QSB      ┆ null      ┆ null      ┆ 342       ┆ … ┆ 40000000  ┆ null      ┆ Học Bạ    ┆ Sử dụng   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ QSB      ┆ null      ┆ null      ┆ 258       ┆ … ┆ 80000000  ┆ null      ┆ Học Bạ    ┆ Sử dụng   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ QSB      ┆ null      ┆ null      ┆ 211       ┆ … ┆ 80000000  ┆ null      ┆ Học Bạ    ┆ Sử dụng   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [5]:
qsb = pl.read_csv("../../data/priority-admission-data.csv")

In [6]:
qsb = qsb.filter(pl.col("uni_code")=="QSB")

In [7]:
qsb = qsb.with_columns(
    # 1. Thay thế chữ "Ưu Tiên" thành "Tổng Hợp" trong cột admission_code
    pl.col("admission_code").str.replace("Ưu Tiên", "Tổng Hợp"),

    # 2. Set lại toàn bộ cột admission_type_name thành chuỗi cố định
    pl.lit("Sử dụng phương thức tổng hợp").alias("admission_type_name")
).drop("subject_combination")

In [8]:
qsb

shape: (66, 12)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ admission_ ┆ uni_code ┆ uni_name  ┆ major_cod ┆ … ┆ tuition_f ┆ province  ┆ uni_type ┆ uni_web_l │
│ code       ┆ ---      ┆ ---       ┆ e         ┆   ┆ ee        ┆ ---       ┆ ---      ┆ ink       │
│ ---        ┆ str      ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str      ┆ ---       │
│ str        ┆          ┆           ┆ str       ┆   ┆ i64       ┆           ┆          ┆ str       │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ QSB-129-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7520309   ┆ … ┆ 30000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-237-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7520212   ┆ … ┆ 80000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-141-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7510211   ┆ … ┆ 30000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-142-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7520130   ┆ … ┆ 30000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-310-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7520114   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ QSB-211-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7520114   ┆ … ┆ 80000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-315-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7580201   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-215-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 758       ┆ … ┆ 80000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-306-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7480101   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ QSB-342-Tổ ┆ QSB      ┆ TRƯỜNG    ┆ 7520130   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│ ng Hợp     ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [9]:
qsb = qsb.with_columns(
    pl.col("admission_code")
    .str.split("-")          # 1. Tách chuỗi dựa trên dấu "-"
    .list.get(1)             # 2. Lấy phần tử thứ 2 (index 1) trong list kết quả
    .alias("admission_code") # 3. Ghi đè lại vào cột cũ
)

In [10]:
qsb

shape: (66, 12)
┌────────────┬──────────┬───────────┬───────────┬───┬───────────┬───────────┬──────────┬───────────┐
│ admission_ ┆ uni_code ┆ uni_name  ┆ major_cod ┆ … ┆ tuition_f ┆ province  ┆ uni_type ┆ uni_web_l │
│ code       ┆ ---      ┆ ---       ┆ e         ┆   ┆ ee        ┆ ---       ┆ ---      ┆ ink       │
│ ---        ┆ str      ┆ str       ┆ ---       ┆   ┆ ---       ┆ str       ┆ str      ┆ ---       │
│ str        ┆          ┆           ┆ str       ┆   ┆ i64       ┆           ┆          ┆ str       │
╞════════════╪══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪══════════╪═══════════╡
│ 129        ┆ QSB      ┆ TRƯỜNG    ┆ 7520309   ┆ … ┆ 30000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 237        ┆ QSB      ┆ TRƯỜNG    ┆ 7520212   ┆ … ┆ 80000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 141        ┆ QSB      ┆ TRƯỜNG    ┆ 7510211   ┆ … ┆ 30000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 142        ┆ QSB      ┆ TRƯỜNG    ┆ 7520130   ┆ … ┆ 30000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 310        ┆ QSB      ┆ TRƯỜNG    ┆ 7520114   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ …          ┆ …        ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …        ┆ …         │
│ 211        ┆ QSB      ┆ TRƯỜNG    ┆ 7520114   ┆ … ┆ 80000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 315        ┆ QSB      ┆ TRƯỜNG    ┆ 7580201   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 215        ┆ QSB      ┆ TRƯỜNG    ┆ 758       ┆ … ┆ 80000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 306        ┆ QSB      ┆ TRƯỜNG    ┆ 7480101   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
│ 342        ┆ QSB      ┆ TRƯỜNG    ┆ 7520130   ┆ … ┆ 40000000  ┆ TP. Hồ    ┆ Công lập ┆ https://h │
│            ┆          ┆ ĐẠI HỌC   ┆           ┆   ┆           ┆ Chí Minh  ┆          ┆ cmut.edu. │
│            ┆          ┆ BÁCH      ┆           ┆   ┆           ┆           ┆          ┆ vn        │
│            ┆          ┆ KHOA-ĐẠI  ┆           ┆   ┆           ┆           ┆          ┆           │
│            ┆          ┆ H…        ┆           ┆   ┆           ┆           ┆          ┆           │
└────────────┴──────────┴───────────┴───────────┴───┴───────────┴───────────┴──────────┴───────────┘

In [11]:
import polars as pl

# Giả sử bạn đã có 2 dataframe là df và qsb

# 1. Thực hiện Merge (Left Join)
# - left_on="major_code": Key của df
# - right_on="admission_code": Key của qsb
# - suffix="_qsb": Đổi tên các cột trùng từ qsb để tránh lỗi duplicate column
merged = df.join(
    qsb, 
    left_on="major_code", 
    right_on="admission_code", 
    how="left", 
    suffix="_qsb"
)

# 2. Xác định các cột chung cần điền dữ liệu (Fill Null)
# Lấy danh sách cột có ở cả 2 bảng (trừ cột key major_code/admission_code ra vì tên khác nhau)
common_cols = [col for col in df.columns if col in qsb.columns]

# 3. Thực hiện Fill Null & Select
# Logic: Với mỗi cột chung, update giá trị bằng cột _qsb nếu cột gốc bị null
final_df = merged.with_columns([
    pl.col(c).fill_null(pl.col(f"{c}_qsb")) for c in common_cols
]).select(
    # Giữ lại toàn bộ cột ban đầu của df
    df.columns
)

# Hiển thị kết quả
print(final_df)

shape: (150, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ uni_code ┆ uni_name  ┆ uni_web_l ┆ major_cod ┆ … ┆ tuition_f ┆ study_pro ┆ admission ┆ admission │
│ ---      ┆ ---       ┆ ink       ┆ e         ┆   ┆ ee        ┆ gram      ┆ _type     ┆ _type_nam │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ e         │
│          ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140231V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140246V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210403V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210404V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7220201BP ┆ … ┆ 30000000  ┆ Đào tạo   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆ tại Bình  ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆ Phước     ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 308       ┆ … ┆ 40000000  ┆ Chương    ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình     ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ chuyển    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ tiếp quốc ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 146       ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 342       ┆ … ┆ 40000000  ┆ Chương    ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình     ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ chuyển    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ tiếp quốc ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 258       ┆ … ┆ 80000000  ┆ Chương    ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình dạy ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ và học    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ bằng t…   ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 211       ┆ … ┆ 80000000  ┆ Chương    ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình dạy ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ và học    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ bằng t…   ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [12]:
final_df = final_df.with_columns(
    # Cập nhật cột admission_type
    pl.when(pl.col("uni_code") == "QSB")
    .then(pl.lit("Tổng Hợp"))
    .otherwise(pl.col("admission_type"))
    .alias("admission_type"),

    # Cập nhật cột admission_type_name
    pl.when(pl.col("uni_code") == "QSB")
    .then(pl.lit("Sử dụng phương thức xét tuyển tổng hợp"))
    .otherwise(pl.col("admission_type_name"))
    .alias("admission_type_name")
)

In [13]:
final_df

shape: (150, 13)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ uni_code ┆ uni_name  ┆ uni_web_l ┆ major_cod ┆ … ┆ tuition_f ┆ study_pro ┆ admission ┆ admission │
│ ---      ┆ ---       ┆ ink       ┆ e         ┆   ┆ ee        ┆ gram      ┆ _type     ┆ _type_nam │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ ---       ┆ e         │
│          ┆           ┆ str       ┆ str       ┆   ┆ i64       ┆ str       ┆ str       ┆ ---       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ str       │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140231V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140246V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210403V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210404V  ┆ … ┆ 30000000  ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7220201BP ┆ … ┆ 30000000  ┆ Đào tạo   ┆ Học Bạ    ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆ tại Bình  ┆           ┆ phương    │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆ Phước     ┆           ┆ thức xét  │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 308       ┆ … ┆ 40000000  ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình     ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ chuyển    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ tiếp quốc ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 146       ┆ … ┆ 30000000  ┆ Đại trà   ┆ Tổng Hợp  ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆           ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆           ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆           ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 342       ┆ … ┆ 40000000  ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình     ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ chuyển    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ tiếp quốc ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆ …         ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 258       ┆ … ┆ 80000000  ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình dạy ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ và học    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ bằng t…   ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 211       ┆ … ┆ 80000000  ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆ trình dạy ┆           ┆ phương    │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆ và học    ┆           ┆ thức xét  │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆ bằng t…   ┆           ┆ tuyển …   │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
final_df = final_df.with_columns(
    pl.concat_str(
        [
            pl.col("uni_code"), 
            pl.col("major_code"), 
            pl.col("admission_type")
        ],
        separator="-"
    ).alias("admission_code")
)

In [15]:
final_df

shape: (150, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ uni_code ┆ uni_name  ┆ uni_web_l ┆ major_cod ┆ … ┆ study_pro ┆ admission ┆ admission ┆ admission │
│ ---      ┆ ---       ┆ ink       ┆ e         ┆   ┆ gram      ┆ _type     ┆ _type_nam ┆ _code     │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│          ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140231V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-71402 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 31V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140246V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-71402 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 46V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210403V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-72104 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 03V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210404V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-72104 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 04V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7220201BP ┆ … ┆ Đào tạo   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-72202 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆ tại Bình  ┆           ┆ phương    ┆ 01BP-Học  │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆ Phước     ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 308       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-308-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình     ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ chuyển    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ tiếp quốc ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆ …         ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 146       ┆ … ┆ Đại trà   ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-146-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 342       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-342-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình     ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ chuyển    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ tiếp quốc ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆ …         ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 258       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-258-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình dạy ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ và học    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ bằng t…   ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 211       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-211-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình dạy ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ và học    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ bằng t…   ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [16]:
final_df = final_df.with_columns(
    pl.col("uni_type").cast(pl.Int64)
)

In [17]:
final_df

shape: (150, 14)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ uni_code ┆ uni_name  ┆ uni_web_l ┆ major_cod ┆ … ┆ study_pro ┆ admission ┆ admission ┆ admission │
│ ---      ┆ ---       ┆ ink       ┆ e         ┆   ┆ gram      ┆ _type     ┆ _type_nam ┆ _code     │
│ str      ┆ str       ┆ ---       ┆ ---       ┆   ┆ ---       ┆ ---       ┆ e         ┆ ---       │
│          ┆           ┆ str       ┆ str       ┆   ┆ str       ┆ str       ┆ ---       ┆ str       │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ str       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140231V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-71402 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 31V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7140246V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-71402 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 46V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210403V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-72104 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 03V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7210404V  ┆ … ┆ Đại trà   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-72104 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆           ┆           ┆ phương    ┆ 04V-Học   │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆           ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ SPK      ┆ TRƯỜNG    ┆ https://h ┆ 7220201BP ┆ … ┆ Đào tạo   ┆ Học Bạ    ┆ Sử dụng   ┆ SPK-72202 │
│          ┆ ĐẠI HỌC   ┆ cmute.edu ┆           ┆   ┆ tại Bình  ┆           ┆ phương    ┆ 01BP-Học  │
│          ┆ SƯ PHẠM   ┆ .vn/      ┆           ┆   ┆ Phước     ┆           ┆ thức xét  ┆ Bạ        │
│          ┆ KỸ THUẬ…  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 308       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-308-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình     ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ chuyển    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ tiếp quốc ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆ …         ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 146       ┆ … ┆ Đại trà   ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-146-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆           ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆           ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆           ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 342       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-342-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình     ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ chuyển    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ tiếp quốc ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆ …         ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 258       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-258-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình dạy ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ và học    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ bằng t…   ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ QSB      ┆ TRƯỜNG    ┆ https://h ┆ 211       ┆ … ┆ Chương    ┆ Tổng Hợp  ┆ Sử dụng   ┆ QSB-211-T │
│          ┆ ĐẠI HỌC   ┆ cmut.edu. ┆           ┆   ┆ trình dạy ┆           ┆ phương    ┆ ổng Hợp   │
│          ┆ BÁCH      ┆ vn        ┆           ┆   ┆ và học    ┆           ┆ thức xét  ┆           │
│          ┆ KHOA-ĐẠI  ┆           ┆           ┆   ┆ bằng t…   ┆           ┆ tuyển …   ┆           │
│          ┆ H…        ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [18]:
import polars as pl
import uuid
from datetime import datetime

# 1. Cấu hình kết nối
connection_uri = "postgresql://myuser:secret@localhost:5433/node_app_dev"

# 2. Hàm sinh UUID và thêm Timestamp
# Vì Polars xử lý vector, cách nhanh nhất để tạo UUID unique cho từng dòng là dùng List Comprehension
uuid_list = [uuid.uuid4() for _ in range(final_df.height)]
current_time = datetime.now().isoformat()
df_to_write = final_df.with_columns(
    # Thêm cột UUID
    pl.Series(name="id", values=uuid_list),
    
    # Thêm cột thời gian
    pl.lit(current_time).alias("created_at"),
    pl.lit(current_time).alias("updated_at")
)


# 3. Ghi vào DB (Schema: machine_learning)
try:
    df_to_write.write_database(
        table_name="machine_learning.l3_transcript_new", # Đã sửa lỗi schema ở đây
        connection=connection_uri,
        if_table_exists="replace",
        engine="sqlalchemy"
    )
    print("✅ Đã tạo UUID và load dữ liệu thành công!")
except Exception as e:
    print(f"❌ Có lỗi xảy ra: {e}")

✅ Đã tạo UUID và load dữ liệu thành công!

In [19]:
from sqlalchemy import create_engine, text
engine = create_engine(connection_uri)
with engine.connect() as conn:
    # Lệnh SQL biến cột id thành KHÓA CHÍNH (Primary Key)
    conn.execute(text("ALTER TABLE machine_learning.l3_transcript_new ADD PRIMARY KEY (id);"))
    conn.commit()
    print("✅ Đã set Primary Key thành công!")

✅ Đã set Primary Key thành công!