In [2]:
import re, json, numpy as np, pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, f1_score, classification_report
import lightgbm as lgb
from pandas.api.types import CategoricalDtype

In [3]:
df = pd.read_excel('../../data/train_l1.xlsx')

In [4]:
df

,Công lập (1/0),Tỉnh/TP,Tổ hợp môn,Học phí,hsg_1,hsg_2,hsg_3,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,truong-nganh-ptxt,nhom_nganh
0,1,An Giang,NaN,14100000.0,Toán,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
1,1,An Giang,NaN,14100000.0,Lý,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
2,1,An Giang,NaN,14100000.0,Hoá,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
3,1,An Giang,NaN,14100000.0,Sinh,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
4,1,An Giang,NaN,14100000.0,Tin,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
...,...,...,...,...,...,...,...,...,...,...,...,...
40910,1,TP. Hồ Chí Minh,C01,62000000.0,0,0,0,0,0,1,SPK-7510303A-Ưu Tiên,751
40911,1,Bình Phước,C01,32000000.0,0,0,0,0,0,1,SPK-7510301BP-Ưu Tiên,751
40912,1,TP. Hồ Chí Minh,C02,32000000.0,0,0,0,0,0,1,SPK-7510401V-Ưu Tiên,751
40913,1,TP. Hồ Chí Minh,A01,49000000.0,0,0,0,0,0,1,SPK-7510205N-Ưu Tiên,751
40914,1,Bình Phước,D01,32000000.0,0,0,0,0,0,1,SPK-7220201BP-Ưu Tiên,722

In [5]:
mask = df["Học phí"].isna()

df.loc[mask, "Học phí"] = df.loc[mask, "truong-nganh-ptxt"].apply(
    lambda x: 0 if str(x).startswith("SPS") 
    else 32000000 if str(x).startswith("SPK") 
    else 60000000 if str(x).startswith("QSX") 
    else np.nan
)

In [6]:
df[df["Học phí"].isna()]["truong-nganh-ptxt"].unique()

array([], dtype=object)

In [7]:
rename_map = {
    "Công lập (1/0)": "cong_lap",
    "Tỉnh/TP": "tinh_tp",
    "Học phí": "hoc_phi",
    "hsg_1": "hsg_1",
    "hsg_2": "hsg_2",
    "hsg_3": "hsg_3",
    "ahld": "ahld",
    "dan_toc_thieu_so": "dan_toc_thieu_so",
    "haimuoi_huyen_ngheo_tnb": "haimuoi_huyen_ngheo_tnb",
    "truong-nganh-ptxt": "truong_nganh_ptxt",
    "nhom_nganh": "nhom_nganh",
    "Tổ hợp môn": "to_hop_mon",
}
df = df.rename(columns=rename_map)

In [8]:
print(df)

       cong_lap          tinh_tp to_hop_mon     hoc_phi hsg_1 hsg_2 hsg_3  \
0             1         An Giang        NaN  14100000.0  Toán     0     0
1             1         An Giang        NaN  14100000.0    Lý     0     0
2             1         An Giang        NaN  14100000.0   Hoá     0     0
3             1         An Giang        NaN  14100000.0  Sinh     0     0
4             1         An Giang        NaN  14100000.0   Tin     0     0
...         ...              ...        ...         ...   ...   ...   ...
40910         1  TP. Hồ Chí Minh        C01  62000000.0     0     0     0
40911         1       Bình Phước        C01  32000000.0     0     0     0
40912         1  TP. Hồ Chí Minh        C02  32000000.0     0     0     0
40913         1  TP. Hồ Chí Minh        A01  49000000.0     0     0     0
40914         1       Bình Phước        D01  32000000.0     0     0     0

       ahld  dan_toc_thieu_so  haimuoi_huyen_ngheo_tnb  \
0         0                 0                        0
1         0                 0                        0
2         0                 0                        0
3         0                 0                        0
4         0                 0                        0
...     ...               ...                      ...
40910     0                 0                        1
40911     0                 0                        1
40912     0                 0                        1
40913     0                 0                        1
40914     0                 0                        1

             truong_nganh_ptxt  nhom_nganh
0      QSA-7140201-TUYỂN THẲNG         714
1      QSA-7140201-TUYỂN THẲNG         714
2      QSA-7140201-TUYỂN THẲNG         714
3      QSA-7140201-TUYỂN THẲNG         714
4      QSA-7140201-TUYỂN THẲNG         714
...                        ...         ...
40910     SPK-7510303A-Ưu Tiên         751
40911    SPK-7510301BP-Ưu Tiên         751
40912     SPK-7510401V-Ưu Tiên         751
40913     SPK-7510205N-Ưu Tiên         751
40914    SPK-7220201BP-Ưu Tiên         722

[40915 rows x 12 columns]

In [9]:
df['cong_lap']  = pd.to_numeric(df['cong_lap'], errors='coerce').fillna(0).astype('int8')
df['hoc_phi']   = pd.to_numeric(df['hoc_phi'],  errors='coerce')
df['nhom_nganh']= pd.to_numeric(df['nhom_nganh'], errors='coerce').astype('Int64')

for c in ['tinh_tp','to_hop_mon','truong_nganh_ptxt']:
    df[c] = df[c].astype(str).replace({'nan':'UNK','None':'UNK'})

prio_cols = ['hsg_1','hsg_2','hsg_3','ahld','dan_toc_thieu_so','haimuoi_huyen_ngheo_tnb']
for c in prio_cols:
    df[c] = df[c].fillna(0)

def pick_hsg(row):
    for k in ['hsg_1','hsg_2','hsg_3']:
        v = row[k]
        if isinstance(v, str) and v != '0' and v.strip() != '':
            return v.strip()
        if isinstance(v, (int, float)) and v != 0:
            return str(v)
    return "0"

df['hsg_subject'] = df.apply(pick_hsg, axis=1)

In [10]:
df

,cong_lap,tinh_tp,to_hop_mon,hoc_phi,hsg_1,hsg_2,hsg_3,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,truong_nganh_ptxt,nhom_nganh,hsg_subject
0,1,An Giang,UNK,14100000.0,Toán,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Toán
1,1,An Giang,UNK,14100000.0,Lý,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Lý
2,1,An Giang,UNK,14100000.0,Hoá,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Hoá
3,1,An Giang,UNK,14100000.0,Sinh,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Sinh
4,1,An Giang,UNK,14100000.0,Tin,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Tin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40910,1,TP. Hồ Chí Minh,C01,62000000.0,0,0,0,0,0,1,SPK-7510303A-Ưu Tiên,751,0
40911,1,Bình Phước,C01,32000000.0,0,0,0,0,0,1,SPK-7510301BP-Ưu Tiên,751,0
40912,1,TP. Hồ Chí Minh,C02,32000000.0,0,0,0,0,0,1,SPK-7510401V-Ưu Tiên,751,0
40913,1,TP. Hồ Chí Minh,A01,49000000.0,0,0,0,0,0,1,SPK-7510205N-Ưu Tiên,751,0
40914,1,Bình Phước,D01,32000000.0,0,0,0,0,0,1,SPK-7220201BP-Ưu Tiên,722,0

## Lightgbm (not good)

In [ ]:
# for c in ['ahld','dan_toc_thieu_so','haimuoi_huyen_ngheo_tnb']:
#     df[c] = (df[c].astype(str) != '0').astype('int8')

# df['prio_any'] = (
#     (df['hsg_subject'] != '0') |
#     (df['ahld'] == 1) |
#     (df['dan_toc_thieu_so'] == 1) |
#     (df['haimuoi_huyen_ngheo_tnb'] == 1)
# ).astype('int8')

In [ ]:
# label_col = 'truong_nganh_ptxt'
# classes, y = np.unique(df[label_col].astype(str).values, return_inverse=True)
# num_class = len(classes)
# num_class

1191

In [ ]:
# cat_cols = [
#     'cong_lap','tinh_tp','hsg_subject',
# ]
# num_cols = [
#     'hoc_phi','nhom_nganh','ahld','dan_toc_thieu_so','haimuoi_huyen_ngheo_tnb'
# ]

# for c in cat_cols:
#     df[c] = df[c].astype('category')
# for c in num_cols:
#     df[c] = pd.to_numeric(df[c], errors='coerce')

# X = df[cat_cols + num_cols]

In [ ]:
# X

,cong_lap,tinh_tp,hsg_subject,hoc_phi,nhom_nganh,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb
0,1,An Giang,Toán,14100000.0,714,0,0,0
1,1,An Giang,Lý,14100000.0,714,0,0,0
2,1,An Giang,Hoá,14100000.0,714,0,0,0
3,1,An Giang,Sinh,14100000.0,714,0,0,0
4,1,An Giang,Tin,14100000.0,714,0,0,0
...,...,...,...,...,...,...,...,...
40910,1,TP. Hồ Chí Minh,0,62000000.0,751,0,0,1
40911,1,Bình Phước,0,32000000.0,751,0,0,1
40912,1,TP. Hồ Chí Minh,0,32000000.0,751,0,0,1
40913,1,TP. Hồ Chí Minh,0,49000000.0,751,0,0,1
40914,1,Bình Phước,0,32000000.0,722,0,0,1

In [ ]:
# def round_budget_series(s: pd.Series) -> pd.Series:
#     x = pd.to_numeric(s, errors='coerce').fillna(0).astype(float)
#     bins   = [-np.inf, 0, 10e6, 20e6, 40e6, 60e6, 80e6, 100e6, 200e6, np.inf]
#     labels = [0,        10e6,  20e6,  40e6,  60e6,  80e6,  100e6,  200e6, 500e6]
#     return pd.cut(x, bins=bins, labels=labels, right=True, include_lowest=True).astype(float).astype('int64')

# data = X.copy()
# data['hoc_phi_ceiled'] = round_budget_series(data['hoc_phi']).astype('int64')

In [ ]:
# data

,cong_lap,tinh_tp,hsg_subject,hoc_phi,nhom_nganh,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,hoc_phi_ceiled,fee_bin_idx,is_free
0,1,An Giang,Toán,14100000.0,714,0,0,0,20000000,2,0
1,1,An Giang,Lý,14100000.0,714,0,0,0,20000000,2,0
2,1,An Giang,Hoá,14100000.0,714,0,0,0,20000000,2,0
3,1,An Giang,Sinh,14100000.0,714,0,0,0,20000000,2,0
4,1,An Giang,Tin,14100000.0,714,0,0,0,20000000,2,0
...,...,...,...,...,...,...,...,...,...,...,...
40910,1,TP. Hồ Chí Minh,0,62000000.0,751,0,0,1,80000000,5,0
40911,1,Bình Phước,0,32000000.0,751,0,0,1,40000000,3,0
40912,1,TP. Hồ Chí Minh,0,32000000.0,751,0,0,1,40000000,3,0
40913,1,TP. Hồ Chí Minh,0,49000000.0,751,0,0,1,60000000,4,0
40914,1,Bình Phước,0,32000000.0,722,0,0,1,40000000,3,0

In [ ]:
# CAPS = [0,10_000_000,20_000_000,40_000_000,60_000_000,80_000_000,100_000_000,200_000_000,500_000_000]
# cap_to_idx = {cap:i for i,cap in enumerate(CAPS)}
# data['fee_bin_idx'] = data['hoc_phi_ceiled'].map(cap_to_idx).astype('int8')   # feature số/ordered category
# data['is_free']     = (data['hoc_phi_ceiled'] == 0).astype('int8')

In [ ]:
# y

array([491, 491, 491, ..., 850, 833, 797])

In [ ]:
# classes, y_enc = np.unique(y, return_inverse=True)

# X_train, X_valid, y_train, y_valid = train_test_split(
#     data, y_enc, test_size=0.2, random_state=42, stratify=y_enc
# )

# vc = pd.Series(y_train).value_counts()
# cls_w = {int(k): float(1.0/np.sqrt(v)) for k, v in vc.items()}
# w_train = pd.Series(y_train).map(cls_w).astype('float32').values
# w_valid = pd.Series(y_valid).map(cls_w).fillna(float(np.mean(list(cls_w.values())))).astype('float32').values

# d_train = lgb.Dataset(
#     X_train, label=y_train, weight=w_train,
#     categorical_feature=cat_cols, free_raw_data=False
# )
# d_valid = lgb.Dataset(
#     X_valid, label=y_valid, weight=w_valid,   # có thể bỏ weight=... nếu không cần
#     categorical_feature=cat_cols, reference=d_train, free_raw_data=False
# )

In [ ]:
# params = {
#     'objective': 'multiclass',
#     'num_class': len(classes),
#     'metric': 'multi_logloss',
#     'learning_rate': 0.05,
#     'num_leaves': 63,
#     'min_data_in_leaf': 20,
#     'feature_fraction': 0.8,
#     'bagging_fraction': 0.9,
#     'bagging_freq': 1,
#     'verbose': -1,
#     'seed': 42,
# }
# clf = lgb.train(
#     params,
#     d_train,
#     num_boost_round=1000,
#     valid_sets=[d_train, d_valid],
#     valid_names=['train','valid'],
#     callbacks=[lgb.early_stopping(150), lgb.log_evaluation(50)]
# )

Training until validation scores don't improve for 150 rounds
[50]	train's multi_logloss: 33.0749	valid's multi_logloss: 33.0536
[100]	train's multi_logloss: 32.6595	valid's multi_logloss: 32.6262
[150]	train's multi_logloss: 33.7011	valid's multi_logloss: 33.732
Early stopping, best iteration is:
[1]	train's multi_logloss: 4.82171	valid's multi_logloss: 4.69209

In [ ]:
# p_valid = clf.predict(X_valid, num_iteration=getattr(clf, "best_iteration", None))

# from sklearn.preprocessing import label_binarize
# from sklearn.metrics import precision_recall_fscore_support

# num_class = p_valid.shape[1]
# Y_true = label_binarize(y_valid, classes=np.arange(num_class))  # one-hot ground truth
# thr = 0.05  # ngưỡng xác suất để chọn label
# Y_pred = (p_valid >= thr).astype(int)

# # micro/samples (samples = tính theo từng hàng rồi trung bình)
# p_micro, r_micro, f_micro, _     = precision_recall_fscore_support(Y_true, Y_pred, average="micro",   zero_division=0)
# p_samples, r_samples, f_samples, _ = precision_recall_fscore_support(Y_true, Y_pred, average="samples", zero_division=0)

# print({
#     "precision_micro_thr": p_micro, "recall_micro_thr": r_micro, "f1_micro_thr": f_micro,
#     "precision_samples_thr": p_samples, "recall_samples_thr": r_samples, "f1_samples_thr": f_samples,
#     "threshold": thr
# })

{'precision_micro_thr': 0.27721786736344406, 'recall_micro_thr': 0.5445435659293658, 'f1_micro_thr': 0.3673991012903492, 'precision_samples_thr': 0.3428311016451063, 'recall_samples_thr': 0.5445435659293658, 'f1_samples_thr': 0.3918180160572926, 'threshold': 0.05}

## per-group classifier (LogisticRegression/MultinomialNB)

In [11]:
from sklearn.preprocessing import OneHotEncoder, LabelEncoder
from sklearn.linear_model import LogisticRegression

In [52]:
group_cols   = ['tinh_tp','nhom_nganh']
target_col   = 'truong_nganh_ptxt'
ohe_cols     = ['cong_lap','tinh_tp','nhom_nganh','hsg_subject',
                'ahld','dan_toc_thieu_so','haimuoi_huyen_ngheo_tnb',]

# CAPS = [0,10_000_000,20_000_000,40_000_000,60_000_000,80_000_000,100_000_000,200_000_000,500_000_000]
# cap_to_idx = {cap:i for i,cap in enumerate(CAPS)}
# def round_budget_series(s: pd.Series) -> pd.Series:
#     x = pd.to_numeric(s, errors='coerce').fillna(0).astype(float)
#     bins   = [-np.inf, 0, 10e6, 20e6, 40e6, 60e6, 80e6, 100e6, 200e6, np.inf]
#     labels = [0,        10e6,  20e6,  40e6,  60e6,  80e6,  100e6,  200e6, 500e6]
#     return pd.cut(x, bins=bins, labels=labels, right=True, include_lowest=True).astype(float).astype('int64')

# df: pd.DataFrame = df.copy()
# df['fee_bin_idx'] = round_budget_series(df['hoc_phi']).map(cap_to_idx).fillna(0).astype('int8')

In [13]:
for c in ['tinh_tp','hsg_subject', target_col]:
    df[c] = df[c].astype(str).replace({'nan':'UNK','None':'UNK'})

In [106]:
df

,cong_lap,tinh_tp,to_hop_mon,hoc_phi,hsg_1,hsg_2,hsg_3,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,truong_nganh_ptxt,nhom_nganh,hsg_subject
0,1,An Giang,UNK,14100000.0,Toán,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Toán
1,1,An Giang,UNK,14100000.0,Lý,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Lý
2,1,An Giang,UNK,14100000.0,Hoá,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Hoá
3,1,An Giang,UNK,14100000.0,Sinh,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Sinh
4,1,An Giang,UNK,14100000.0,Tin,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714,Tin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
40910,1,TP. Hồ Chí Minh,C01,62000000.0,0,0,0,0,0,1,SPK-7510303A-Ưu Tiên,751,0
40911,1,Bình Phước,C01,32000000.0,0,0,0,0,0,1,SPK-7510301BP-Ưu Tiên,751,0
40912,1,TP. Hồ Chí Minh,C02,32000000.0,0,0,0,0,0,1,SPK-7510401V-Ưu Tiên,751,0
40913,1,TP. Hồ Chí Minh,A01,49000000.0,0,0,0,0,0,1,SPK-7510205N-Ưu Tiên,751,0
40914,1,Bình Phước,D01,32000000.0,0,0,0,0,0,1,SPK-7220201BP-Ưu Tiên,722,0

In [107]:
df[df["truong_nganh_ptxt"]=="DBD-7220201-TUYỂN THẲNG"]

,cong_lap,tinh_tp,to_hop_mon,hoc_phi,hsg_1,hsg_2,hsg_3,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,truong_nganh_ptxt,nhom_nganh,hsg_subject
2249,1,Bình Dương,UNK,16262000.0,Toán,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Toán
2250,1,Bình Dương,UNK,16262000.0,Lý,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Lý
2251,1,Bình Dương,UNK,16262000.0,Hoá,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Hoá
2252,1,Bình Dương,UNK,16262000.0,Sinh,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Sinh
2253,1,Bình Dương,UNK,16262000.0,Tin,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tin
2254,1,Bình Dương,UNK,16262000.0,Văn,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Văn
2255,1,Bình Dương,UNK,16262000.0,Sử,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Sử
2256,1,Bình Dương,UNK,16262000.0,Địa,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Địa
2257,1,Bình Dương,UNK,16262000.0,Anh,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Anh
2258,1,Bình Dương,UNK,16262000.0,Tiếng Pháp,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Pháp
2259,1,Bình Dương,UNK,16262000.0,Tiếng Trung,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Trung
2260,1,Bình Dương,UNK,16262000.0,Tiếng Nhật,0,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Nhật
14704,1,Bình Dương,UNK,16262000.0,0,Toán,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Toán
14705,1,Bình Dương,UNK,16262000.0,0,Lý,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Lý
14706,1,Bình Dương,UNK,16262000.0,0,Hoá,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Hoá
14707,1,Bình Dương,UNK,16262000.0,0,Sinh,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Sinh
14708,1,Bình Dương,UNK,16262000.0,0,Tin,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tin
14709,1,Bình Dương,UNK,16262000.0,0,Văn,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Văn
14710,1,Bình Dương,UNK,16262000.0,0,Sử,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Sử
14711,1,Bình Dương,UNK,16262000.0,0,Địa,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Địa
14712,1,Bình Dương,UNK,16262000.0,0,Anh,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Anh
14713,1,Bình Dương,UNK,16262000.0,0,Tiếng Pháp,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Pháp
14714,1,Bình Dương,UNK,16262000.0,0,Tiếng Trung,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Trung
14715,1,Bình Dương,UNK,16262000.0,0,Tiếng Nhật,0,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Nhật
27155,1,Bình Dương,UNK,16262000.0,0,0,Toán,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Toán
27156,1,Bình Dương,UNK,16262000.0,0,0,Lý,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Lý
27157,1,Bình Dương,UNK,16262000.0,0,0,Hoá,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Hoá
27158,1,Bình Dương,UNK,16262000.0,0,0,Sinh,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Sinh
27159,1,Bình Dương,UNK,16262000.0,0,0,Tin,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tin
27160,1,Bình Dương,UNK,16262000.0,0,0,Văn,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Văn
27161,1,Bình Dương,UNK,16262000.0,0,0,Sử,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Sử
27162,1,Bình Dương,UNK,16262000.0,0,0,Địa,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Địa
27163,1,Bình Dương,UNK,16262000.0,0,0,Anh,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Anh
27164,1,Bình Dương,UNK,16262000.0,0,0,Tiếng Pháp,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Pháp
27165,1,Bình Dương,UNK,16262000.0,0,0,Tiếng Trung,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Trung
27166,1,Bình Dương,UNK,16262000.0,0,0,Tiếng Nhật,0,0,0,DBD-7220201-TUYỂN THẲNG,722,Tiếng Nhật
37568,1,Bình Dương,UNK,16262000.0,0,0,0,1,0,0,DBD-7220201-TUYỂN THẲNG,722,0
38759,1,Bình Dương,UNK,16262000.0,0,0,0,0,1,0,DBD-7220201-TUYỂN THẲNG,722,0
39950,1,Bình Dương,UNK,16262000.0,0,0,0,0,0,1,DBD-7220201-TUYỂN THẲNG,722,0

In [53]:
num_groups = df.groupby(group_cols, dropna=False).ngroups
print("Số nhóm:", num_groups)

Số nhóm: 133

In [14]:
models = {}            
encoders = {}          
label_encoders = {}   
class_lists = {} 

for gkey, gdf in df.groupby(group_cols, dropna=False):
    # label encoding per group
    y_text = gdf[target_col].astype(str).values
    le = LabelEncoder()
    y = le.fit_transform(y_text)

    if np.unique(y).size <= 1:
        models[gkey] = None
        encoders[gkey] = None
        label_encoders[gkey] = le
        class_lists[gkey] = le.classes_.tolist()
        continue

    enc = OneHotEncoder(handle_unknown='ignore', sparse_output=False, dtype=np.float32)
    Xg = enc.fit_transform(gdf[ohe_cols].astype(str))

    clf = LogisticRegression(
        max_iter=1000,
        solver='lbfgs',
        multi_class='auto',
        class_weight='balanced',
        n_jobs=None
    )

    clf.fit(Xg, y)

    models[gkey] = clf
    encoders[gkey] = enc
    label_encoders[gkey] = le
    class_lists[gkey] = le.classes_.tolist()

len(models)

/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(
/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:1264: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(

133

In [18]:
clf

LogisticRegression(class_weight='balanced', max_iter=1000, multi_class='auto')

In [20]:
cong_lap = [1,0]
tinh_tp = ["TP. Hồ Chí Minh","An Giang","Bình Dương","Cần Thơ","Vũng Tàu"]
hoc_phi = [0,10000000,20000000,40000000,60000000,80000000,100000000,200000000,500000000]
hsg_subject = ["Toán", "Lý", "Anh", "Văn", "Hoá", "Sinh", "Tin", "Sử", "Địa", "Tiếng Pháp", "Tiếng Trung", "Tiếng Nhật", "Tiếng Nga"]
nhom_nganh = [714, 734, 738, 742, 748, 751, 754, 762, 731, 722, 785, 764, 721, 746, 758,
772, 781, 732, 752, 784, 776, 744]
ahld = [0, 1]
dan_toc_thieu_so = [0, 1]
haimuoi_huyen_ngheo_tnb = [0, 1]

test = pd.DataFrame({
    'cong_lap': np.random.choice(cong_lap, size=100),
    'tinh_tp': np.random.choice(tinh_tp, size=100),
    'hoc_phi': np.random.choice(hoc_phi, size=100),
    'nhom_nganh': np.random.choice(nhom_nganh, size=100),
    'hsg_subject': np.random.choice(hsg_subject, size=100),
    'ahld': np.random.choice(ahld, size=100),
    'dan_toc_thieu_so': np.random.choice(dan_toc_thieu_so, size=100),
    'haimuoi_huyen_ngheo_tnb': np.random.choice(haimuoi_huyen_ngheo_tnb, size=100),
})
import pandas as pd

# đảm bảo dtype
test = test.copy()
test['hsg_subject'] = test['hsg_subject'].fillna("0").astype(str)
for c in ['ahld', 'dan_toc_thieu_so', 'haimuoi_huyen_ngheo_tnb']:
    test[c] = pd.to_numeric(test[c], errors='coerce').fillna(0).astype(int)

rows = []

hsg_df = test[test['hsg_subject'] != "0"].copy()
hsg_df[['ahld', 'dan_toc_thieu_so', 'haimuoi_huyen_ngheo_tnb']] = 0
rows.append(hsg_df)

ahld_df = test[test['ahld'] == 1].copy()
ahld_df['hsg_subject'] = "0"
ahld_df[['dan_toc_thieu_so', 'haimuoi_huyen_ngheo_tnb']] = 0
rows.append(ahld_df)

dtts_df = test[test['dan_toc_thieu_so'] == 1].copy()
dtts_df['hsg_subject'] = "0"
dtts_df[['ahld', 'haimuoi_huyen_ngheo_tnb']] = 0
rows.append(dtts_df)

huyen_df = test[test['haimuoi_huyen_ngheo_tnb'] == 1].copy()
huyen_df['hsg_subject'] = "0"
huyen_df[['ahld', 'dan_toc_thieu_so']] = 0
rows.append(huyen_df)

none_df = test[
    (test['hsg_subject'] == "0") &
    (test['ahld'] == 0) &
    (test['dan_toc_thieu_so'] == 0) &
    (test['haimuoi_huyen_ngheo_tnb'] == 0)
].copy()
rows.append(none_df)

# Gộp & loại bỏ mọi dòng còn >1 ưu tiên
out = pd.concat(rows, ignore_index=True)

active_cnt = (
    (out['hsg_subject'] != "0").astype(int)
    + out['ahld'].astype(int)
    + out['dan_toc_thieu_so'].astype(int)
    + out['haimuoi_huyen_ngheo_tnb'].astype(int)
)
out = out[active_cnt <= 1].reset_index(drop=True)
out

,cong_lap,tinh_tp,hoc_phi,nhom_nganh,hsg_subject,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb
0,1,TP. Hồ Chí Minh,20000000,742,Văn,0,0,0
1,0,Vũng Tàu,100000000,746,Tiếng Nhật,0,0,0
2,1,Bình Dương,40000000,734,Sinh,0,0,0
3,1,Cần Thơ,500000000,734,Văn,0,0,0
4,1,An Giang,100000000,776,Anh,0,0,0
...,...,...,...,...,...,...,...,...
242,1,Cần Thơ,10000000,784,0,0,0,1
243,0,TP. Hồ Chí Minh,200000000,746,0,0,0,1
244,0,Cần Thơ,80000000,748,0,0,0,1
245,1,An Giang,60000000,751,0,0,0,1
246,1,Cần Thơ,40000000,738,0,0,0,1

In [21]:
out.columns

Index(['cong_lap', 'tinh_tp', 'hoc_phi', 'nhom_nganh', 'hsg_subject', 'ahld',
       'dan_toc_thieu_so', 'haimuoi_huyen_ngheo_tnb'],
      dtype='object')

In [26]:
l1_ori = pd.read_excel('../../data/l1_rs.xlsx')

In [ ]:
l1_ori.columns

Index(['Unnamed: 0', 'Công lập (1/0)', 'Tỉnh/TP', 'Tổ hợp môn', 'hoc_phi',
       'hsg_1', 'hsg_2', 'hsg_3', 'ahld', 'dan_toc_thieu_so',
       'haimuoi_huyen_ngheo_tnb', 'major_uni', 'nhom_nganh'],
      dtype='object')

In [30]:
l1_ori = l1_ori.drop(columns=['Unnamed: 0', 'Tổ hợp môn'])

In [32]:
l1_ori

,Công lập (1/0),Tỉnh/TP,hoc_phi,hsg_1,hsg_2,hsg_3,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,major_uni,nhom_nganh
0,1,An Giang,14100000.0,Toán,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
1,1,An Giang,14100000.0,Lý,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
2,1,An Giang,14100000.0,Hoá,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
3,1,An Giang,14100000.0,Sinh,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
4,1,An Giang,14100000.0,Tin,0,0,0,0,0,QSA-7140201-TUYỂN THẲNG,714
...,...,...,...,...,...,...,...,...,...,...,...
40766,1,TP. Hồ Chí Minh,58000000.0,0,0,0,0,0,1,SPK-7510303A-Ưu Tiên,751
40767,1,Bình Phước,32000000.0,0,0,0,0,0,1,SPK-7510301BP-Ưu Tiên,751
40768,1,TP. Hồ Chí Minh,32000000.0,0,0,0,0,0,1,SPK-7510401V-Ưu Tiên,751
40769,1,TP. Hồ Chí Minh,49000000.0,0,0,0,0,0,1,SPK-7510205N-Ưu Tiên,751
40770,1,Bình Phước,32000000.0,0,0,0,0,0,1,SPK-7220201BP-Ưu Tiên,722

In [65]:
import polars as pl
for col in l1_ori.columns:
    if l1_ori[col].dtype == 'object':
        l1_ori[col] = l1_ori[col].astype(str)

for col in out.columns:  # test dataframe
    if out[col].dtype == 'object':
        out[col] = out[col].astype(str)

test = pl.DataFrame(out)
l1 = pl.DataFrame(l1_ori)

test = test.rename({"hoc_phi": "hoc_phi_test"})
test = test.rename({"ahld": "ahld_test"})
test = test.rename({"dan_toc_thieu_so": "dan_toc_thieu_so_test"})
test = test.rename({"nhom_nganh": "nhom_nganh_test"})
test = test.rename({"haimuoi_huyen_ngheo_tnb": "haimuoi_huyen_ngheo_tnb_test"})

l1 = l1.rename({"hoc_phi": "hoc_phi_l1"})
l1 = l1.rename({"ahld": "ahld_l1"})
l1 = l1.rename({"dan_toc_thieu_so": "dan_toc_thieu_so_l1"})
l1 = l1.rename({"nhom_nganh": "nhom_nganh_l1"})
l1 = l1.rename({"haimuoi_huyen_ngheo_tnb": "haimuoi_huyen_ngheo_tnb_l1"})

matches = (
    test.lazy()
    .join(l1.lazy(), how="cross")
    .with_columns([
        (
            (pl.col("cong_lap") == pl.col("Công lập (1/0)")) &
            (pl.col("tinh_tp") == pl.col("Tỉnh/TP")) &
            (pl.col("hoc_phi_test") >= pl.col("hoc_phi_l1")) &
            ((pl.col("hsg_subject") == pl.col("hsg_1")) |
             (pl.col("hsg_subject") == pl.col("hsg_2")) |
             (pl.col("hsg_subject") == pl.col("hsg_3"))) &
            (pl.col("ahld_test") == pl.col("ahld_l1")) &
            (pl.col("dan_toc_thieu_so_test") == pl.col("dan_toc_thieu_so_l1")) &
            (pl.col("haimuoi_huyen_ngheo_tnb_test") == pl.col("haimuoi_huyen_ngheo_tnb_l1")) &
            (pl.col("nhom_nganh_test") == pl.col("nhom_nganh_l1"))
        ).alias("match")
    ])
    .filter(pl.col("match"))  # chỉ giữ các dòng thỏa
    .group_by(["cong_lap", "tinh_tp", "hoc_phi_test", "nhom_nganh_test",
              "hsg_subject", "ahld_test", "dan_toc_thieu_so_test", "haimuoi_huyen_ngheo_tnb_test"])
    .agg(pl.col("major_uni").alias("label"))  # gom tất cả major_uni thành list
)

test_with_label = (
    test.lazy()
    .join(matches, on=["cong_lap","tinh_tp","hoc_phi_test","nhom_nganh_test",
                       "hsg_subject","ahld_test","dan_toc_thieu_so_test",
                       "haimuoi_huyen_ngheo_tnb_test"], how="left")
    .with_columns([
        pl.when(pl.col("label").is_null())
          .then(pl.lit(None))
          .otherwise(pl.col("label"))
          .alias("label")
    ])
    .collect()
)

In [66]:
test_with_label

shape: (247, 9)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cong_lap ┆ tinh_tp   ┆ hoc_phi_t ┆ nhom_ngan ┆ … ┆ ahld_test ┆ dan_toc_t ┆ haimuoi_h ┆ label     │
│ ---      ┆ ---       ┆ est       ┆ h_test    ┆   ┆ ---       ┆ hieu_so_t ┆ uyen_nghe ┆ ---       │
│ i64      ┆ str       ┆ ---       ┆ ---       ┆   ┆ i64       ┆ est       ┆ o_tnb_tes ┆ list[str] │
│          ┆           ┆ i64       ┆ i64       ┆   ┆           ┆ ---       ┆ t         ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆ ---       ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ i64       ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ TP. Hồ    ┆ 20000000  ┆ 742       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ ["SPS-742 │
│          ┆ Chí Minh  ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0203-Ưu   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ Tiên",    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "SPS-7…   │
│ 0        ┆ Vũng Tàu  ┆ 100000000 ┆ 746       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ null      │
│ 1        ┆ Bình      ┆ 40000000  ┆ 734       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ ["DBD-734 │
│          ┆ Dương     ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0101-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "D…       │
│ 1        ┆ Cần Thơ   ┆ 500000000 ┆ 734       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ ["TCT-734 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0101-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "T…       │
│ 1        ┆ An Giang  ┆ 100000000 ┆ 776       ┆ … ┆ 0         ┆ 0         ┆ 0         ┆ null      │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1        ┆ Cần Thơ   ┆ 10000000  ┆ 784       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ null      │
│ 0        ┆ TP. Hồ    ┆ 200000000 ┆ 746       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ null      │
│          ┆ Chí Minh  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0        ┆ Cần Thơ   ┆ 80000000  ┆ 748       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ null      │
│ 1        ┆ An Giang  ┆ 60000000  ┆ 751       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ ["QSA-751 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0406-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "Q…       │
│ 1        ┆ Cần Thơ   ┆ 40000000  ┆ 738       ┆ … ┆ 0         ┆ 0         ┆ 1         ┆ ["TCT-738 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ 0101-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆           ┆ "T…       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [90]:
type(test_with_label)

polars.dataframe.frame.DataFrame

In [92]:
test_with_label = test_with_label.with_columns(
    pl.col("label").list.unique().alias("uni_label")
)

In [93]:
test_with_label

shape: (247, 10)
┌──────────┬───────────┬───────────┬───────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ cong_lap ┆ tinh_tp   ┆ hoc_phi_t ┆ nhom_ngan ┆ … ┆ dan_toc_t ┆ haimuoi_h ┆ label     ┆ uni_label │
│ ---      ┆ ---       ┆ est       ┆ h_test    ┆   ┆ hieu_so_t ┆ uyen_nghe ┆ ---       ┆ ---       │
│ i64      ┆ str       ┆ ---       ┆ ---       ┆   ┆ est       ┆ o_tnb_tes ┆ list[str] ┆ list[str] │
│          ┆           ┆ i64       ┆ i64       ┆   ┆ ---       ┆ t         ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆ i64       ┆ ---       ┆           ┆           │
│          ┆           ┆           ┆           ┆   ┆           ┆ i64       ┆           ┆           │
╞══════════╪═══════════╪═══════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 1        ┆ TP. Hồ    ┆ 20000000  ┆ 742       ┆ … ┆ 0         ┆ 0         ┆ ["SPS-742 ┆ ["SPS-742 │
│          ┆ Chí Minh  ┆           ┆           ┆   ┆           ┆           ┆ 0203-Ưu   ┆ 0203-Ưu   │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ Tiên",    ┆ Tiên"]    │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ "SPS-7…   ┆           │
│ 0        ┆ Vũng Tàu  ┆ 100000000 ┆ 746       ┆ … ┆ 0         ┆ 0         ┆ null      ┆ null      │
│ 1        ┆ Bình      ┆ 40000000  ┆ 734       ┆ … ┆ 0         ┆ 0         ┆ ["DBD-734 ┆ ["TDM-734 │
│          ┆ Dương     ┆           ┆           ┆   ┆           ┆           ┆ 0101-TUYỂ ┆ 0302-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ N THẲNG", ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ "D…       ┆ "T…       │
│ 1        ┆ Cần Thơ   ┆ 500000000 ┆ 734       ┆ … ┆ 0         ┆ 0         ┆ ["TCT-734 ┆ ["TCT-734 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0101-TUYỂ ┆ 0121-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ N THẲNG", ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ "T…       ┆ "T…       │
│ 1        ┆ An Giang  ┆ 100000000 ┆ 776       ┆ … ┆ 0         ┆ 0         ┆ null      ┆ null      │
│ …        ┆ …         ┆ …         ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …         │
│ 1        ┆ Cần Thơ   ┆ 10000000  ┆ 784       ┆ … ┆ 0         ┆ 1         ┆ null      ┆ null      │
│ 0        ┆ TP. Hồ    ┆ 200000000 ┆ 746       ┆ … ┆ 0         ┆ 1         ┆ null      ┆ null      │
│          ┆ Chí Minh  ┆           ┆           ┆   ┆           ┆           ┆           ┆           │
│ 0        ┆ Cần Thơ   ┆ 80000000  ┆ 748       ┆ … ┆ 0         ┆ 1         ┆ null      ┆ null      │
│ 1        ┆ An Giang  ┆ 60000000  ┆ 751       ┆ … ┆ 0         ┆ 1         ┆ ["QSA-751 ┆ ["QSA-751 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0406-TUYỂ ┆ 0401-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ N THẲNG", ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ "Q…       ┆ "Q…       │
│ 1        ┆ Cần Thơ   ┆ 40000000  ┆ 738       ┆ … ┆ 0         ┆ 1         ┆ ["TCT-738 ┆ ["TCT-738 │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ 0101-TUYỂ ┆ 0101-TUYỂ │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ N THẲNG", ┆ N THẲNG", │
│          ┆           ┆           ┆           ┆   ┆           ┆           ┆ "T…       ┆ "T…       │
└──────────┴───────────┴───────────┴───────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [94]:
def predict(df):
    records = []
    for idx, r in df.iterrows():
        gkey = tuple(r[c] for c in group_cols)
        clf = models.get(gkey)
        enc = encoders.get(gkey)
        le  = label_encoders.get(gkey)

        if le is None:
            records.append({
                'row_id': idx,
                'group': gkey,
                'status': 'unseen_group',
                'pred': None,
                'probs': None
            })
            continue

        if clf is None:
            # single-class group -> deterministic prediction
            only_label = le.classes_[0]
            records.append({
                'row_id': idx,
                'group': gkey,
                'status': 'single_class',
                'pred': only_label,
                'probs': {only_label: 1.0}
            })
            continue

        # one-hot transform with this group's encoder
        X1 = enc.transform(pd.DataFrame([r[ohe_cols].astype(str)]))
        if hasattr(clf, "predict_proba"):
            p = clf.predict_proba(X1)[0]
            labels = le.classes_
            items = list(zip(labels, p))
            items.sort(key=lambda x: -x[1])
            
            pred = items[0][0]
            probs = {lab: float(pr) for lab, pr in items}
        else:
            # NB always has predict_proba; this is a fallback
            yhat = clf.predict(X1)[0]
            pred = le.inverse_transform([yhat])[0]
            probs = None

        records.append({
            'row_id': idx,
            'group': gkey,
            'status': 'ok',
            'pred': pred,
            'probs': probs
        })

    return pd.DataFrame(records)
pred_df = predict(out)

In [95]:
print(pred_df)

     row_id                   group        status                     pred  \
0         0  (TP. Hồ Chí Minh, 742)            ok  DCT-7420201-TUYỂN THẲNG
1         1         (Vũng Tàu, 746)  unseen_group                     None
2         2       (Bình Dương, 734)            ok  VGU-7340101-TUYỂN THẲNG
3         3          (Cần Thơ, 734)            ok  TCT-7340101-TUYỂN THẲNG
4         4         (An Giang, 776)  unseen_group                     None
..      ...                     ...           ...                      ...
242     242          (Cần Thơ, 784)  unseen_group                     None
243     243  (TP. Hồ Chí Minh, 746)            ok  FUV-7460112-TUYỂN THẲNG
244     244          (Cần Thơ, 748)            ok  TCT-7480101-TUYỂN THẲNG
245     245         (An Giang, 751)            ok  QSA-7510401-TUYỂN THẲNG
246     246          (Cần Thơ, 738)            ok  TCT-7380101-TUYỂN THẲNG

                                                 probs
0    {'DCT-7420201-TUYỂN THẲNG': 0.0745626552284294...
1                                                 None
2    {'VGU-7340101-TUYỂN THẲNG': 0.0883176683658808...
3    {'TCT-7340101-TUYỂN THẲNG': 0.1, 'TCT-7340101_...
4                                                 None
..                                                 ...
242                                               None
243  {'FUV-7460112-TUYỂN THẲNG': 0.8743064616074306...
244  {'TCT-7480101-TUYỂN THẲNG': 0.1, 'TCT-7480102-...
245  {'QSA-7510401-TUYỂN THẲNG': 0.5, 'QSA-7510406-...
246  {'TCT-7380101-TUYỂN THẲNG': 0.5, 'TCT-7380107-...

[247 rows x 5 columns]

In [96]:
def get_all_labels(probs):
    if probs is None:
        return None
    return list(probs.keys())

pred_df['y_predict'] = pred_df['probs'].apply(get_all_labels)

In [97]:
l1_ori.columns

Index(['Công lập (1/0)', 'Tỉnh/TP', 'hoc_phi', 'hsg_1', 'hsg_2', 'hsg_3',
       'ahld', 'dan_toc_thieu_so', 'haimuoi_huyen_ngheo_tnb', 'major_uni',
       'nhom_nganh'],
      dtype='object')

In [98]:
# Tạo lookup {major_uni: hoc_phi}
l1_hoc_phi_dict = dict(zip(l1_ori['major_uni'], l1_ori['hoc_phi']))

def filter_labels_by_hoc_phi(y_pred_list, test_hoc_phi, lookup):
    if y_pred_list is None:
        return None
    # chỉ giữ nhãn thỏa hoc_phi
    return [label for label in y_pred_list if test_hoc_phi >= lookup.get(label, 0)]

# Áp dụng
pred_df['y_predict_filtered'] = [
    filter_labels_by_hoc_phi(y_pred, test_hoc_phi, l1_hoc_phi_dict)
    for y_pred, test_hoc_phi in zip(pred_df['y_predict'], test_with_label['hoc_phi_test'])
]

In [79]:
out

,cong_lap,tinh_tp,hoc_phi,nhom_nganh,hsg_subject,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb
0,1,TP. Hồ Chí Minh,20000000,742,Văn,0,0,0
1,0,Vũng Tàu,100000000,746,Tiếng Nhật,0,0,0
2,1,Bình Dương,40000000,734,Sinh,0,0,0
3,1,Cần Thơ,500000000,734,Văn,0,0,0
4,1,An Giang,100000000,776,Anh,0,0,0
...,...,...,...,...,...,...,...,...
242,1,Cần Thơ,10000000,784,0,0,0,1
243,0,TP. Hồ Chí Minh,200000000,746,0,0,0,1
244,0,Cần Thơ,80000000,748,0,0,0,1
245,1,An Giang,60000000,751,0,0,0,1
246,1,Cần Thơ,40000000,738,0,0,0,1

In [102]:
y_pred = [
    lbl if lbl is not None else [] 
    for lbl in pred_df['y_predict_filtered']
]

y_true = [
    lbl if lbl is not None else [] 
    for lbl in test_with_label['uni_label']
]

In [103]:
y_pred

[['SPS-7420203-Ưu Tiên'],
 [],
 ['DBD-7340201-TUYỂN THẲNG',
  'DBD-7340301-TUYỂN THẲNG',
  'DBD-7340101-TUYỂN THẲNG',
  'TDM-7340101-TUYỂN THẲNG',
  'TDM-7340302-TUYỂN THẲNG',
  'TDM-7340301-TUYỂN THẲNG',
  'TDM-7340115-TUYỂN THẲNG',
  'TDM-7340201-TUYỂN THẲNG',
  'TDM-7340122-TUYỂN THẲNG',
  'DKB-7340301-TUYỂN THẲNG',
  'DKB-7340122-TUYỂN THẲNG',
  'DKB-7340115-TUYỂN THẲNG',
  'DKB-7340101-TUYỂN THẲNG',
  'DKB-7340201-TUYỂN THẲNG',
  'DKB-7340406-TUYỂN THẲNG'],
 ['TCT-7340101-TUYỂN THẲNG',
  'TCT-7340101_CLC-TUYỂN THẲNG',
  'TCT-7340115-TUYỂN THẲNG',
  'TCT-7340120-TUYỂN THẲNG',
  'TCT-7340120_CLC-TUYỂN THẲNG',
  'TCT-7340121-TUYỂN THẲNG',
  'TCT-7340201-TUYỂN THẲNG',
  'TCT-7340201_CLC-TUYỂN THẲNG',
  'TCT-7340301-TUYỂN THẲNG',
  'TCT-7340302-TUYỂN THẲNG'],
 [],
 [],
 ['QSA-7310106-TUYỂN THẲNG', 'QSA-7310630-TUYỂN THẲNG'],
 [],
 [],
 ['QSB-237-Ưu Tiên',
  'QSB-208-Ưu Tiên',
  'QSB-211-Ưu Tiên',
  'QSB-220-Ưu Tiên',
  'QSB-242-Ưu Tiên',
  'QSB-245-Ưu Tiên',
  'QSB-342-Ưu Tiên',
  'QSB-145-Ưu Tiên',
  'QSB-308-Ưu Tiên',
  'QSB-258-Ưu Tiên',
  'QSB-345-Ưu Tiên',
  'QSB-120-Ưu Tiên',
  'SPK-7520401V-Ưu Tiên',
  'SPK-7520117V-Ưu Tiên',
  'SPK-7520212V-Ưu Tiên',
  'SPK-7520212A-Ưu Tiên',
  'QSB-314-Ưu Tiên',
  'QSB-214-Ưu Tiên',
  'QSB-138-Ưu Tiên',
  'QSB-268-Ưu Tiên',
  'QSB-137-Ưu Tiên',
  'QSB-325-Ưu Tiên',
  'UTC2-7520116-TUYỂN THẲNG',
  'QSB-129-Ưu Tiên',
  'QSB-229-Ưu Tiên',
  'UTC2-7520130-TUYỂN THẲNG',
  'UTC2-7520201-TUYỂN THẲNG',
  'UTC2-7520114-TUYỂN THẲNG',
  'UTC2-7520216-TUYỂN THẲNG',
  'UTC2-7520207-TUYỂN THẲNG',
  'QSB-310-Ưu Tiên',
  'QSB-140-Ưu Tiên',
  'QSB-109-Ưu Tiên',
  'QSB-210-Ưu Tiên',
  'QSB-228-Ưu Tiên',
  'QSB-309-Ưu Tiên',
  'QSB-128-Ưu Tiên',
  'QSB-209-Ưu Tiên',
  'GTS-7520116-TUYỂN THẲNG',
  'PTIT2-7520216-TUYỂN THẲNG',
  'GTS-7520130-TUYỂN THẲNG',
  'HHK-7520120E-TUYỂN THẲNG',
  'GTS-7520216-TUYỂN THẲNG',
  'GTS-7520207-TUYỂN THẲNG',
  'GTS-7520114-TUYỂN THẲNG',
  'GTS-7520201-TUYỂN THẲNG',
  'HHK-7520120-TUYỂN THẲNG',
  'DCT-7520115-TUYỂN THẲNG',
  'PTIT2-7520208-TUYỂN THẲNG',
  'PTIT2-7520207-TUYỂN THẲNG',
  'QSQ-7520212-Ưu Tiên',
  'QSQ-7520118_SB-Ưu Tiên',
  'QST-7520207_DKD-Ưu Tiên',
  'QSQ-7520207_SB-Ưu Tiên',
  'QST-7520403-Ưu Tiên',
  'MTU-7520320-Ưu Tiên',
  'QSQ-7520118-Ưu Tiên',
  'QST-7520402-Ưu Tiên',
  'QSC-752020a1-Ưu Tiên',
  'DTT-FA7520216-Ưu Tiên',
  'DTT-K7520201-Ưu Tiên',
  'QSQ-7520207-Ưu Tiên',
  'SGD-7520202-Ưu Tiên',
  'QST-7520501-Ưu Tiên',
  'QSQ-7520301-Ưu Tiên',
  'QSQ-7520207_WE-Ưu Tiên',
  'QST-7520207_NN-Ưu Tiên',
  'SGD-7520201-Ưu Tiên',
  'QSQ-7520216-Ưu Tiên',
  'QSQ-7520121-Ưu Tiên',
  'SGD-7520207-Ưu Tiên'],
 [],
 [],
 ['TCT-7510401-TUYỂN THẲNG',
  'TCT-7510401_CLC-TUYỂN THẲNG',
  'TCT-7510601-TUYỂN THẲNG',
  'TCT-7510605-TUYỂN THẲNG'],
 ['TDM-7210201-TUYỂN THẲNG', 'TDM-7210403-TUYỂN THẲNG'],
 ['SPS-7140219-Ưu Tiên',
  'SPS-7140206-Ưu Tiên',
  'SPS-7140202-Ưu Tiên',
  'SPS-7140233-Ưu Tiên',
  'SGD-7140222-Ưu Tiên',
  'SPS-7140212-Ưu Tiên',
  'SPS-7140231_LA-Ưu Tiên',
  'SPS-7140217-Ưu Tiên',
  'SPS-7140210-Ưu Tiên',
  'SPS-7140202_LA-Ưu Tiên',
  'SPS-7140231-Ưu Tiên',
  'SPS-7140217_LA-Ưu Tiên',
  'SPS-7140201_LA-Ưu Tiên',
  'SPS-7140249-Ưu Tiên',
  'SPS-7140204-Ưu Tiên',
  'SPS-7140246-Ưu Tiên',
  'SPS-7140218-Ưu Tiên',
  'SPS-7140234-Ưu Tiên',
  'SPS-7140213-Ưu Tiên',
  'SGD-7140221-Ưu Tiên',
  'SPS-7140209-Ưu Tiên',
  'SPS-7140208-Ưu Tiên',
  'SPS-7140203-Ưu Tiên',
  'SPS-7140209_LA-Ưu Tiên',
  'SPS-7140247-Ưu Tiên',
  'SPS-7140205-Ưu Tiên',
  'SPS-7140201-Ưu Tiên',
  'SPS-7140232-Ưu Tiên',
  'SPS-7140211-Ưu Tiên',
  'SPS-7140206_LA-Ưu Tiên',
  'SGD-7140205-Ưu Tiên',
  'SGD-7140212-Ưu Tiên',
  'SGD-7140217-Ưu Tiên',
  'SGD-7140231-Ưu Tiên',
  'SGD-7140218-Ưu Tiên',
  'SGD-7140213-Ưu Tiên',
  'SGD-7140247-Ưu Tiên',
  'SGD-7140202-Ưu Tiên',
  'SGD-7140219-Ưu Tiên',
  'SGD-7140201-Ưu Tiên',
  'SGD-7140209-Ưu Tiên',
  'SPS-7140101-Ưu Tiên',
  'SPS-7140114-Ưu Tiên',
  'SGD-7140211-Ưu Tiên',
  'SGD-7140249-Ưu Tiên'],
 [],
 [],
 ['DBD-7510102-TUYỂN THẲNG',
  'TDM-7510205-TUYỂN THẲNG',
  'TDM-7510601-TUYỂN THẲNG',
  'TDM-7510605-TUYỂN THẲNG',
  'DBD-7510205-TUYỂN THẲNG',
  'DBD-7510605-TUYỂN THẲNG',
  'DBD-7510301-TUYỂN THẲNG',
  'DKB-7510301-TUYỂN THẲNG',
  'DKB-7510205-TUYỂN THẲNG',
  'DKB-7510605-TUYỂN THẲNG'],
 ['TCT-7480101-TUYỂN THẲNG',
  'TCT-7480102-TUYỂN THẲNG',
  'TCT-7480103-TUYỂN THẲNG',
  'TCT-7480103_CLC-TUYỂN THẲNG',
  'TCT-7480104-TUYỂN THẲNG',
  'TCT-7480104_CLC-TUYỂN THẲNG',
  'TCT-7480106-TUYỂN THẲNG',
  'TCT-7480201-TUYỂN THẲNG',
  'TCT-7480201_CLC-TUYỂN THẲNG',
  'TCT-7480202-TUYỂN THẲNG'],
 ['TCT-7320101-TUYỂN THẲNG', 'TCT-7320201-TUYỂN THẲNG'],
 [],
 [],
 ['QST-7440301_DKD-Ưu Tiên',
  'QST-7440228-Ưu Tiên',
  'SGD-7440301-Ưu Tiên',
  'QST-7440112_DKD-Ưu Tiên',
  'QST-7440102_DKD-Ưu Tiên',
  'QST-7440122_DKD-Ưu Tiên',
  'SPS-7440102-Ưu Tiên',
  'QST-7440201_NN-Ưu Tiên',
  'QST-7440102_NN-Ưu Tiên',
  'QSQ-7440112-Ưu Tiên',
  'QST-7440122-Ưu Tiên',
  'QST-7440301-Ưu Tiên',
  'QST-7440112-Ưu Tiên',
  'SPS-7440112-Ưu Tiên'],
 ['TCT-7340101-TUYỂN THẲNG',
  'TCT-7340101_CLC-TUYỂN THẲNG',
  'TCT-7340115-TUYỂN THẲNG',
  'TCT-7340120-TUYỂN THẲNG',
  'TCT-7340120_CLC-TUYỂN THẲNG',
  'TCT-7340121-TUYỂN THẲNG',
  'TCT-7340201-TUYỂN THẲNG',
  'TCT-7340201_CLC-TUYỂN THẲNG',
  'TCT-7340301-TUYỂN THẲNG',
  'TCT-7340302-TUYỂN THẲNG'],
 ['DBD-7480201-TUYỂN THẲNG'],
 ['SPK-7840110V-Ưu Tiên',
  'HHK-7840102E-TUYỂN THẲNG',
  'HHK-7840102-TUYỂN THẲNG',
  'HHK-7840104K-TUYỂN THẲNG',
  'HHK-7840104L-TUYỂN THẲNG',
  'GTS-7840101-TUYỂN THẲNG',
  'HHK-7840104E-TUYỂN THẲNG',
  'UTC2-7840101-TUYỂN THẲNG'],
 [],
 ['DBD-7720203-TUYỂN THẲNG'],
 [],
 ['FUV-8449001-TUYỂN THẲNG',
  'QST-7440301_DKD-Ưu Tiên',
  'QST-7440228-Ưu Tiên',
  'SGD-7440301-Ưu Tiên',
  'QST-7440112_DKD-Ưu Tiên',
  'QST-7440102_DKD-Ưu Tiên',
  'QST-7440122_DKD-Ưu Tiên',
  'SPS-7440102-Ưu Tiên',
  'QST-7440201_NN-Ưu Tiên',
  'QSQ-7440112-Ưu Tiên',
  'QST-7440102_NN-Ưu Tiên',
  'QST-7440122-Ưu Tiên',
  'QST-7440301-Ưu Tiên',
  'QST-7440112-Ưu Tiên',
  'SPS-7440112-Ưu Tiên'],
 [],
 [],
 ['HIU-7720701-TUYỂN THẲNG',
  'HIU-7720301-TUYỂN THẲNG',
  'HIU-7720603-TUYỂN THẲNG',
  'HIU-7720115-TUYỂN THẲNG',
  'HIU-7720201-TUYỂN THẲNG',
  'HIU-7720401-TUYỂN THẲNG',
  'HIU-7720601-TUYỂN THẲNG',
  'HIU-7720302-TUYỂN THẲNG',
  'IUH-7720201-TUYỂN THẲNG',
  'IUH-7720497-TUYỂN THẲNG',
  'TYS-7720701-Ưu Tiên',
  'TYS-7720602-Ưu Tiên',
  'TYS-7720699-Ưu Tiên',
  'TYS-7720301-Ưu Tiên',
  'TYS-7720401-Ưu Tiên',
  'TYS-7720601-Ưu Tiên',
  'TYS-7720603-Ưu Tiên',
  'TYS-7720302-Ưu Tiên',
  'TYS-7720201-Ưu Tiên',
  'TYS-7720501-Ưu Tiên',
  'TYS-7720115-Ưu Tiên',
  'TYS-7720101-Ưu Tiên',
  'YDS-7720203-TUYỂN THẲNG',
  'YDS-7720601-TUYỂN THẲNG',
  'YDS-7720201-TUYỂN THẲNG',
  'QSY-7720201-TUYỂN THẲNG',
  'YDS-7720301-TUYỂN THẲNG',
  'YDS-7720603-TUYỂN THẲNG',
  'YDS-7720110-TUYỂN THẲNG',
  'YDS-7720302-TUYỂN THẲNG',
  'YDS-7720502-TUYỂN THẲNG',
  'YDS-7720602-TUYỂN THẲNG',
  'YDS-7720701-TUYỂN THẲNG',
  'YDS-7720401-TUYỂN THẲNG',
  'YDS-7720115-TUYỂN THẲNG',
  'QSY-7720301-TUYỂN THẲNG',
  'QSY-7720115-TUYỂN THẲNG',
  'QSY-7720501-TUYỂN THẲNG',
  'QSY-7720101-TUYỂN THẲNG',
  'YDS-7720101-TUYỂN THẲNG',
  'YDS-7720501-TUYỂN THẲNG'],
 ['TCT-7420101-TUYỂN THẲNG',
  'TCT-7420201-TUYỂN THẲNG',
  'TCT-7420201_TT-TUYỂN THẲNG',
  'TCT-7420203-TUYỂN THẲNG'],
 [],
 [],
 ['HHK-7840102E-TUYỂN THẲNG',
  'HHK-7840102-TUYỂN THẲNG',
  'HHK-7840104K-TUYỂN THẲNG',
  'HHK-7840104L-TUYỂN THẲNG',
  'GTS-7840101-TUYỂN THẲNG',
  'HHK-7840104E-TUYỂN THẲNG',
  'SPK-7840110V-Ưu Tiên',
  'UTC2-7840101-TUYỂN THẲNG'],
 [],
 ['USLA2-7760101-TUYỂN THẲNG',
  'MBS-7760101-TUYỂN THẲNG',
  'QSX-7760101-Ưu Tiên',
  'SPS-7760101-Ưu Tiên'],
 ['DKB-7480201-TUYỂN THẲNG',
  'DKB-7480103-TUYỂN THẲNG',
  'DBD-7480201-TUYỂN THẲNG',
  'TDM-7480103-TUYỂN THẲNG',
  'TDM-7480201-TUYỂN THẲNG',
  'VGU-7480101-TUYỂN THẲNG'],
 [],
 [],
 [],
 ['SPK-7580103V-Ưu Tiên',
  'SPK-7580101V-Ưu Tiên',
  'SPK-7580302V-Ưu Tiên',
  'SPK-7580205V-Ưu Tiên',
  'KTS-7580105_CLC-TUYỂN THẲNG',
  'KTS-7580101-TUYỂN THẲNG',
  'KTS-7580201_CLC-TUYỂN THẲNG',
  'GTS-7580101-TUYỂN THẲNG',
  'KTS-7580102-TUYỂN THẲNG',
  'GTS-7580205-TUYỂN THẲNG',
  'MBS-7580302-TUYỂN THẲNG',
  'GTS-7580301-TUYỂN THẲNG',
  'KTS-7580210-TUYỂN THẲNG',
  'KTS-7580105-TUYỂN THẲNG',
  'KTS-7580108-TUYỂN THẲNG',
  'IUH-7580201-TUYỂN THẲNG',
  'IUH-7580205-TUYỂN THẲNG',
  'KTS-7580101_CLC-TUYỂN THẲNG',
  'IUH-7580302-TUYỂN THẲNG',
  'HSU-7580108-TUYỂN THẲNG',
  'KTS-7580201-TUYỂN THẲNG',
  'GTS-7580302-TUYỂN THẲNG',
  'GTS-7580201-TUYỂN THẲNG',
  'KTS-7580302-TUYỂN THẲNG',
  'MTU-7580106-Ưu Tiên',
  'DTT-7580105-Ưu Tiên',
  'DTT-FA7580201-Ưu Tiên',
  'QSQ-7580302-Ưu Tiên',
  'MTU-7580205-Ưu Tiên',
  'QSQ-7580201_DK-Ưu Tiên',
  'QSQ-7580201-Ưu Tiên',
  'QSX-7580112-Ưu Tiên',
  'MTU-7580213-Ưu Tiên',
  'MTU-7580202-Ưu Tiên',
  'DTT-K7580201-Ưu Tiên',
  'TLU2-TLS104-TUYỂN THẲNG',
  'TLU2-TLS102-TUYỂN THẲNG',
  'TLU2-TLS114-TUYỂN THẲNG',
  'TLU2-TLS404-TUYỂN THẲNG',
  'TLU2-TLS101-TUYỂN THẲNG',
  'TLU2-TLS107-TUYỂN THẲNG',
  'UTC2-7580201-TUYỂN THẲNG',
  'UTC2-7580101-TUYỂN THẲNG',
  'UTC2-7580205-TUYỂN THẲNG',
  'UTC2-7580301-TUYỂN THẲNG',
  'UTC2-7580302-TUYỂN THẲNG',
  'QSB-217-Ưu Tiên',
  'QSB-148-Ưu Tiên',
  'QSB-315-Ưu Tiên',
  'QSB-147-Ưu Tiên',
  'QSB-215-Ưu Tiên',
  'QSB-115-Ưu Tiên',
  'QSB-117-Ưu Tiên',
  'HIU-7580101-TUYỂN THẲNG',
  'DTT-7580205-Ưu Tiên'],
 ['QSA-7640101-TUYỂN THẲNG'],
 ['TCT-7420101-TUYỂN THẲNG',
  'TCT-7420201-TUYỂN THẲNG',
  'TCT-7420201_TT-TUYỂN THẲNG',
  'TCT-7420203-TUYỂN THẲNG'],
 ['SPS-7140219-Ưu Tiên',
  'SPS-7140206-Ưu Tiên',
  'SPS-7140202-Ưu Tiên',
  'SPS-7140233-Ưu Tiên',
  'SGD-7140222-Ưu Tiên',
  'SPS-7140212-Ưu Tiên',
  'SPS-7140231_LA-Ưu Tiên',
  'SPS-7140217-Ưu Tiên',
  'SPS-7140210-Ưu Tiên',
  'SPS-7140202_LA-Ưu Tiên',
  'SPS-7140231-Ưu Tiên',
  'SPS-7140217_LA-Ưu Tiên',
  'QSX-7140101-Ưu Tiên',
  'SPS-7140201_LA-Ưu Tiên',
  'SPS-7140249-Ưu Tiên',
  'SPS-7140204-Ưu Tiên',
  'SPS-7140246-Ưu Tiên',
  'SPS-7140218-Ưu Tiên',
  'SPS-7140234-Ưu Tiên',
  'SPS-7140213-Ưu Tiên',
  'SGD-7140221-Ưu Tiên',
  'SPS-7140209-Ưu Tiên',
  'SPS-7140208-Ưu Tiên',
  'SPS-7140203-Ưu Tiên',
  'SPS-7140209_LA-Ưu Tiên',
  'QSX-7140114-Ưu Tiên',
  'SPS-7140247-Ưu Tiên',
  'SPS-7140205-Ưu Tiên',
  'SPS-7140201-Ưu Tiên',
  'SPS-7140232-Ưu Tiên',
  'SPS-7140211-Ưu Tiên',
  'SPS-7140206_LA-Ưu Tiên',
  'SPK-7140231V-Ưu Tiên',
  'SPK-7140246V-Ưu Tiên',
  'HIU-7140114-TUYỂN THẲNG',
  'SGD-7140205-Ưu Tiên',
  'SGD-7140212-Ưu Tiên',
  'SGD-7140217-Ưu Tiên',
  'SGD-7140231-Ưu Tiên',
  'SGD-7140218-Ưu Tiên',
  'SGD-7140213-Ưu Tiên',
  'SGD-7140247-Ưu Tiên',
  'SGD-7140202-Ưu Tiên',
  'SGD-7140219-Ưu Tiên',
  'SGD-7140201-Ưu Tiên',
  'SGD-7140209-Ưu Tiên',
  'SPS-7140101-Ưu Tiên',
  'SPS-7140114-Ưu Tiên',
  'SGD-7140114-Ưu Tiên',
  'SGD-7140211-Ưu Tiên',
  'SGD-7140249-Ưu Tiên'],
 [],
 [],
 ['QSA-7220201-TUYỂN THẲNG',
  'QSA-7229001-TUYỂN THẲNG',
  'QSA-7229030-TUYỂN THẲNG'],
 [],
 ['DKB-7220201-TUYỂN THẲNG',
  'DKB-7220210-TUYỂN THẲNG',
  'TDM-7220210-TUYỂN THẲNG',
  'TDM-7220204-TUYỂN THẲNG',
  'TDM-7220201-TUYỂN THẲNG',
  'DBD-7220201-TUYỂN THẲNG'],
 ['QSA-7220201-TUYỂN THẲNG',
  'QSA-7229001-TUYỂN THẲNG',
  'QSA-7229030-TUYỂN THẲNG'],
 ['SPK-7310403V-Ưu Tiên',
  'MBS-7310620-TUYỂN THẲNG',
  'MBS-7310301-TUYỂN THẲNG',
  'MBS-7310101C-TUYỂN THẲNG',
  'MBS-7310401-TUYỂN THẲNG',
  'MBS-7310101-TUYỂN THẲNG',
  'NHS-7310106-TUYỂN THẲNG',
  'HCH-7310205-TUYỂN THẲNG',
  'HCH-7310101-TUYỂN THẲNG',
  'USLA2-7310101-TUYỂN THẲNG',
  'USLA2-7310401-TUYỂN THẲNG',
  'QSX-7310613-Ưu Tiên',
  'QSX-73106a1-Ưu Tiên',
  'QSX-7310601-Ưu Tiên',
  'QSX-7310403-Ưu Tiên',
  'QSX-7310630-Ưu Tiên',
  'DTT-N7310630-Ưu Tiên',
  'QSX-7310501-Ưu Tiên',
  'QSX-7310302-Ưu Tiên',
  'QSX-7310206-Ưu Tiên',
  'QSX-7310301-Ưu Tiên',
  'QSX-7310608-Ưu Tiên',
  'QSX-7310614-Ưu Tiên',
  'QSX-7310401-Ưu Tiên',
  'SGD-7310601-Ưu Tiên',
  'SGD-7310630-Ưu Tiên',
  'SPS-7310630-Ưu Tiên',
  'SGD-7310401-Ưu Tiên',
  'SPS-7310403-Ưu Tiên',
  'SGD-7310501-Ưu Tiên',
  'SPS-7310601-Ưu Tiên',
  'SPS-7310501-Ưu Tiên'],
 ['QSA-7140201-TUYỂN THẲNG',
  'QSA-7140202-TUYỂN THẲNG',
  'QSA-7140205-TUYỂN THẲNG',
  'QSA-7140209-TUYỂN THẲNG',
  'QSA-7140211-TUYỂN THẲNG',
  'QSA-7140212-TUYỂN THẲNG',
  'QSA-7140213-TUYỂN THẲNG',
  'QSA-7140217-TUYỂN THẲNG',
  'QSA-7140218-TUYỂN THẲNG',
  'QSA-7140219-TUYỂN THẲNG',
  'QSA-7140231-TUYỂN THẲNG',
  'QSA-7140247-TUYỂN THẲNG'],
 ['PVU-7480101-TUYỂN THẲNG'],
 ['UTC2-7840101-TUYỂN THẲNG'],
 [],
 ['QSA-7480103-TUYỂN THẲNG', 'QSA-7480201-TUYỂN THẲNG'],
 [],
 [],
 [],
 ['QSA-7140201-TUYỂN THẲNG',
  'QSA-7140202-TUYỂN THẲNG',
  'QSA-7140205-TUYỂN THẲNG',
  'QSA-7140209-TUYỂN THẲNG',
  'QSA-7140211-TUYỂN THẲNG',
  'QSA-7140212-TUYỂN THẲNG',
  'QSA-7140213-TUYỂN THẲNG',
  'QSA-7140217-TUYỂN THẲNG',
  'QSA-7140218-TUYỂN THẲNG',
  'QSA-7140219-TUYỂN THẲNG',
  'QSA-7140231-TUYỂN THẲNG',
  'QSA-7140247-TUYỂN THẲNG'],
 ['DBD-7720203-TUYỂN THẲNG'],
 ['TCT-7310101-TUYỂN THẲNG',
  'TCT-7310201-TUYỂN THẲNG',
  'TCT-7310301-TUYỂN THẲNG'],
 [],
 [],
 [],
 [],
 [],
 ['IUH-7720497-TUYỂN THẲNG',
  'IUH-7720201-TUYỂN THẲNG',
  'TYS-7720701-Ưu Tiên',
  'TYS-7720301-Ưu Tiên',
  'TYS-7720602-Ưu Tiên',
  'TYS-7720699-Ưu Tiên',
  'TYS-7720401-Ưu Tiên',
  'TYS-7720601-Ưu Tiên',
  'TYS-7720603-Ưu Tiên',
  'TYS-7720302-Ưu Tiên',
  'TYS-7720501-Ưu Tiên',
  'TYS-7720115-Ưu Tiên',
  'TYS-7720201-Ưu Tiên',
  'TYS-7720101-Ưu Tiên',
  'YDS-7720201-TUYỂN THẲNG',
  'YDS-7720203-TUYỂN THẲNG',
  'YDS-7720601-TUYỂN THẲNG',
  'QSY-7720201-TUYỂN THẲNG',
  'YDS-7720301-TUYỂN THẲNG',
  'YDS-7720603-TUYỂN THẲNG',
  'YDS-7720302-TUYỂN THẲNG',
  'YDS-7720701-TUYỂN THẲNG',
  'YDS-7720110-TUYỂN THẲNG',
  'YDS-7720602-TUYỂN THẲNG',
  'YDS-7720502-TUYỂN THẲNG',
  'YDS-7720401-TUYỂN THẲNG',
  'YDS-7720115-TUYỂN THẲNG',
  'QSY-7720301-TUYỂN THẲNG',
  'QSY-7720115-TUYỂN THẲNG',
  'QSY-7720501-TUYỂN THẲNG',
  'QSY-7720101-TUYỂN THẲNG',
  'YDS-7720101-TUYỂN THẲNG',
  'YDS-7720501-TUYỂN THẲNG',
  'HIU-7720701-TUYỂN THẲNG',
  'HIU-7720301-TUYỂN THẲNG',
  'HIU-7720603-TUYỂN THẲNG',
  'HIU-7720115-TUYỂN THẲNG',
  'HIU-7720201-TUYỂN THẲNG',
  'HIU-7720401-TUYỂN THẲNG',
  'HIU-7720601-TUYỂN THẲNG',
  'HIU-7720302-TUYỂN THẲNG'],
 [],
 ['QSA-7420201-TUYỂN THẲNG'],
 [],
 [],
 ['TDM-7850101-TUYỂN THẲNG', 'TDM-7850103-TUYỂN THẲNG'],
 [],
 [],
 ['IUH-7540101-TUYỂN THẲNG',
  'MBS-7540101-TUYỂN THẲNG',
  'DCT-7540105-TUYỂN THẲNG',
  'DCT-7540204-TUYỂN THẲNG',
  'DCT-7540106-TUYỂN THẲNG',
  'IUH-7540204-TUYỂN THẲNG',
  'IUH-7540106-TUYỂN THẲNG',
  'DCT-7540101-TUYỂN THẲNG',
  'IUH-7540101C-TUYỂN THẲNG',
  'SPK-7540101DD-Ưu Tiên',
  'SPK-7540101V-Ưu Tiên',
  'SPK-7549002V-Ưu Tiên',
  'SPK-7540209V-Ưu Tiên',
  'QSB-112-Ưu Tiên',
  'QSB-319-Ưu Tiên'],
 ['TCT-7320101-TUYỂN THẲNG',
  'TCT-7320104-TUYỂN THẲNG',
  'TCT-7320201-TUYỂN THẲNG'],
 ['HSU-7220204-TUYỂN THẲNG',
  'MBS-7220210-TUYỂN THẲNG',
  'HSU-7220201-TUYỂN THẲNG',
  'MBS-7220201-TUYỂN THẲNG',
  'DCT-7220204-TUYỂN THẲNG',
  'UEF-7220201-TUYỂN THẲNG',
  'UEF-7220210-TUYỂN THẲNG',
  'MBS-7220209C-TUYỂN THẲNG',
  'UEF-7220209-TUYỂN THẲNG',
  'USLA2-7220201-TUYỂN THẲNG',
  'MBS-7220204C-TUYỂN THẲNG',
  'MBS-7220209-TUYỂN THẲNG',
  'MBS-7220201C-TUYỂN THẲNG',
  'HHK-7220201-TUYỂN THẲNG',
  'DCT-7220201-TUYỂN THẲNG',
  'MBS-7220204-TUYỂN THẲNG',
  'IUH-7220201-TUYỂN THẲNG',
  'NHS-7220201_DB-TUYỂN THẲNG',
  'NHS-7220201-TUYỂN THẲNG',
  'UEF-7220204-TUYỂN THẲNG',
  'QSQ-7220201-Ưu Tiên',
  'QSX-7220201_CLC-Ưu Tiên',
  'QSX-7220203-Ưu Tiên',
  'QSX-7220205CLC-Ưu Tiên',
  'QSX-7229009-Ưu Tiên',
  'QSX-7220204_CLC-Ưu Tiên',
  'QSX-7229001-Ưu Tiên',
  'QSX-7229010-Ưu Tiên',
  'QSQ-7220201_WE2-Ưu Tiên',
  'QSX-7220205-Ưu Tiên',
  'QSX-7220202-Ưu Tiên',
  'QSQ-7220201_WE3-Ưu Tiên',
  'QSX-7220206-Ưu Tiên',
  'QSX-7220204-Ưu Tiên',
  'QSX-7229040-Ưu Tiên',
  'SGD-7220201CLC-Ưu Tiên',
  'DTT-N7220201-Ưu Tiên',
  'QSX-7220208-Ưu Tiên',
  'QSQ-7220201_WE4-Ưu Tiên',
  'SPS-7220210-Ưu Tiên',
  'QSX-7229020-Ưu Tiên',
  'SPS-7220209-Ưu Tiên',
  'DTT-FA7220201-Ưu Tiên',
  'QSX-7229030-Ưu Tiên',
  'SPK-7220201V-Ưu Tiên',
  'TLU2-TLS203-TUYỂN THẲNG',
  'HIU-7220210-TUYỂN THẲNG',
  'HIU-7220209-TUYỂN THẲNG',
  'HIU-7220201-TUYỂN THẲNG',
  'HIU-7220204-TUYỂN THẲNG',
  'SGD-7229010-Ưu Tiên',
  'QSX-7220201-Ưu Tiên',
  'SPS-7220202-Ưu Tiên',
  'SGD-7220201-Ưu Tiên',
  'SPS-7229030-Ưu Tiên',
  'FUV-7229030-TUYỂN THẲNG',
  'FUV-7229010-TUYỂN THẲNG'],
 [],
 ['NHS-7340405_TABP-TUYỂN THẲNG',
  'PTIT2-7340115-TUYỂN THẲNG',
  'HCH-7340406-TUYỂN THẲNG',
  'USLA2-7340404-TUYỂN THẲNG',
  'USLA2-7340201-TUYỂN THẲNG',
  'GTS-7340301-TUYỂN THẲNG',
  'IUH-7340120C-TUYỂN THẲNG',
  'MBS-7340205-TUYỂN THẲNG',
  'UEF-7340116-TUYỂN THẲNG',
  'MBS-7340201-TUYỂN THẲNG',
  'FTU2-QTKS2.1-TUYỂN THẲNG',
  'NHS-7340201_TABP-TUYỂN THẲNG',
  'UEF-7340301-TUYỂN THẲNG',
  'MBS-7340404-TUYỂN THẲNG',
  'UEF-7340201-TUYỂN THẲNG',
  'IUH-7340101-TUYỂN THẲNG',
  'NHS-7340201-TUYỂN THẲNG',
  'HHK-7340101E-TUYỂN THẲNG',
  'NHS-7340002-TUYỂN THẲNG',
  'NHS-7340405-TUYỂN THẲNG',
  'DCT-7340123-TUYỂN THẲNG',
  'IUH-7340301-TUYỂN THẲNG',
  'IUH-7340122-TUYỂN THẲNG',
  'GTS-7340101-TUYỂN THẲNG',
  'FTU2-MKTS2.1-TUYỂN THẲNG',
  'HSU-7340301-TUYỂN THẲNG',
  'MBS-7340302C-TUYỂN THẲNG',
  'HSU-7340122-TUYỂN THẲNG',
  'NHS-7340120-TUYỂN THẲNG',
  'UEF-7340302-TUYỂN THẲNG',
  'MBS-7340201C-TUYỂN THẲNG',
  'HSU-7340120-TUYỂN THẲNG',
  'IUH-7340115C-TUYỂN THẲNG',
  'MBS-7340403-TUYỂN THẲNG',
  'IUH-7340122C-TUYỂN THẲNG',
  'UEF-7340206-TUYỂN THẲNG',
  'UEF-7340120-TUYỂN THẲNG',
  'USLA2-7340207-TUYỂN THẲNG',
  'PTIT2-7340101-TUYỂN THẲNG',
  'FTU2-TCHS2.1-TUYỂN THẲNG',
  'MBS-7340301-TUYỂN THẲNG',
  'MBS-7340120-TUYỂN THẲNG',
  'IUH-7340302-TUYỂN THẲNG',
  'UEF-7340115-TUYỂN THẲNG',
  'IUH-7340301Q-TUYỂN THẲNG',
  'PTIT2-7340115_CLC-TUYỂN THẲNG',
  'IUH-7340301C-TUYỂN THẲNG',
  'USLA2-7340301-TUYỂN THẲNG',
  'HHK-7340120-TUYỂN THẲNG',
  'MBS-7340302-TUYỂN THẲNG',
  'HHK-7340404-TUYỂN THẲNG',
  'MBS-7340405-TUYỂN THẲNG',
  'GTS-7340120-TUYỂN THẲNG',
  'IUH-7340120-TUYỂN THẲNG',
  'HSU-7340410-TUYỂN THẲNG',
  'MBS-7340115-TUYỂN THẲNG',
  'NHS-7340115-TUYỂN THẲNG',
  'HSU-7340201-TUYỂN THẲNG',
  'UEF-7340114-TUYỂN THẲNG',
  'HHK-7340101-TUYỂN THẲNG',
  'IUH-7340302C-TUYỂN THẲNG',
  'NHS-7340301_TABP-TUYỂN THẲNG',
  'HSU-7340412-TUYỂN THẲNG',
  'GTS-7340201-TUYỂN THẲNG',
  'USLA2-7340101-TUYỂN THẲNG',
  'DCT-7340129-TUYỂN THẲNG',
  'NHS-7340301-TUYỂN THẲNG',
  'HSU-7340115-TUYỂN THẲNG',
  'UEF-7340412-TUYỂN THẲNG',
  'IUH-7340101C-TUYỂN THẲNG',
  'UEF-7340404-TUYỂN THẲNG',
  'NHS-7340205-TUYỂN THẲNG',
  'MBS-7340101C-TUYỂN THẲNG',
  'DCT-7340122-TUYỂN THẲNG',
  'MBS-7340301C-TUYỂN THẲNG',
  'USLA2-7340405-TUYỂN THẲNG',
  'PTIT2-7340301-TUYỂN THẲNG',
  'NHS-7340101_TABP-TUYỂN THẲNG',
  'MBS-7340204-TUYỂN THẲNG',
  'DCT-7340115-TUYỂN THẲNG',
  'NHS-7340101-TUYỂN THẲNG',
  'UEF-7340205-TUYỂN THẲNG',
  'UEF-7340122-TUYỂN THẲNG',
  'DCT-7340101-TUYỂN THẲNG',
  'UEF-7340121-TUYỂN THẲNG',
  'HSU-7340404-TUYỂN THẲNG',
  'HSU-7340114-TUYỂN THẲNG',
  'IUH-7340115-TUYỂN THẲNG',
  'DCT-7340120-TUYỂN THẲNG',
  'UEF-7340101-TUYỂN THẲNG',
  'MBS-7340101-TUYỂN THẲNG',
  'IUH-7340201-TUYỂN THẲNG',
  'DCT-7340205-TUYỂN THẲNG',
  'DCT-7340301-TUYỂN THẲNG',
  'DCT-7340201-TUYỂN THẲNG',
  'HSU-7340205-TUYỂN THẲNG',
  'IUH-7340201C-TUYỂN THẲNG',
  'IUH-7340302Q-TUYỂN THẲNG',
  'HSU-7340101-TUYỂN THẲNG',
  'DTT-FA7340120-Ưu Tiên',
  'DTT-K7340101-Ưu Tiên',
  'QSQ-7340201-Ưu Tiên',
  'DTT-FA7340301-Ưu Tiên',
  'DTT-N7340101N-Ưu Tiên',
  'DTT-K7340101L-Ưu Tiên',
  'DTT-FA7340201-Ưu Tiên',
  'SGD-7340301CLC-Ưu Tiên',
  'DTT-K7340101N-Ưu Tiên',
  'QSQ-7340301-Ưu Tiên',
  'DTT-K7340201M-Ưu Tiên',
  'DTT-K7340120L-Ưu Tiên',
  'QSQ-7340101_AND-Ưu Tiên',
  'QSQ-7340101_LU-Ưu Tiên',
  'QSQ-7340101_WE4-Ưu Tiên',
  'QSQ-7340101_NS-Ưu Tiên',
  'SGD-7340101CLC-Ưu Tiên',
  'DTT-N7340115-Ưu Tiên',
  'DTT-K7340301-Ưu Tiên',
  'DTT-FA7340101N-Ưu Tiên',
  'QSQ-7340101-Ưu Tiên',
  'DTT-N7340301-Ưu Tiên',
  'DTT-FA7340115-Ưu Tiên',
  'QSQ-7340101_AU-Ưu Tiên',
  'SGD-7340120-Ưu Tiên',
  'QSQ-7340115-Ưu Tiên',
  'DTT-K7340101E-Ưu Tiên',
  'QSX-7340406-Ưu Tiên',

In [104]:
y_true

[shape: (1,)
 Series: '' [str]
 [
 	"SPS-7420203-Ưu Tiên"
 ],
 [],
 shape: (9,)
 Series: '' [str]
 [
 	"TDM-7340302-TUYỂN THẲNG"
 	"TDM-7340101-TUYỂN THẲNG"
 	"DBD-7340101-TUYỂN THẲNG"
 	"DBD-7340201-TUYỂN THẲNG"
 	"DBD-7340301-TUYỂN THẲNG"
 	"TDM-7340115-TUYỂN THẲNG"
 	"TDM-7340301-TUYỂN THẲNG"
 	"TDM-7340201-TUYỂN THẲNG"
 	"TDM-7340122-TUYỂN THẲNG"
 ],
 shape: (10,)
 Series: '' [str]
 [
 	"TCT-7340121-TUYỂN THẲNG"
 	"TCT-7340301-TUYỂN THẲNG"
 	"TCT-7340120-TUYỂN THẲNG"
 	"TCT-7340101_CLC-TUYỂN THẲNG"
 	"TCT-7340201-TUYỂN THẲNG"
 	"TCT-7340302-TUYỂN THẲNG"
 	"TCT-7340115-TUYỂN THẲNG"
 	"TCT-7340101-TUYỂN THẲNG"
 	"TCT-7340120_CLC-TUYỂN THẲNG"
 	"TCT-7340201_CLC-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 shape: (70,)
 Series: '' [str]
 [
 	"QSC-752020a1-Ưu Tiên"
 	"PTIT2-7520216-TUYỂN THẲNG"
 	"QSB-258-Ưu Tiên"
 	"QSB-145-Ưu Tiên"
 	"GTS-7520114-TUYỂN THẲNG"
 	…
 	"QSB-211-Ưu Tiên"
 	"QSQ-7520118-Ưu Tiên"
 	"SPK-7520401V-Ưu Tiên"
 	"QSB-109-Ưu Tiên"
 	"DTT-FA7520216-Ưu Tiên"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (7,)
 Series: '' [str]
 [
 	"DBD-7510605-TUYỂN THẲNG"
 	"DBD-7510301-TUYỂN THẲNG"
 	"DBD-7510102-TUYỂN THẲNG"
 	"TDM-7510205-TUYỂN THẲNG"
 	"DBD-7510205-TUYỂN THẲNG"
 	"TDM-7510601-TUYỂN THẲNG"
 	"TDM-7510605-TUYỂN THẲNG"
 ],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"TCT-7320101-TUYỂN THẲNG"
 	"TCT-7320201-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (11,)
 Series: '' [str]
 [
 	"SPS-7440102-Ưu Tiên"
 	"QST-7440112_DKD-Ưu Tiên"
 	"QST-7440201_NN-Ưu Tiên"
 	"SGD-7440301-Ưu Tiên"
 	"QST-7440301_DKD-Ưu Tiên"
 	…
 	"QST-7440102_NN-Ưu Tiên"
 	"QST-7440102_DKD-Ưu Tiên"
 	"QST-7440228-Ưu Tiên"
 	"QST-7440122_DKD-Ưu Tiên"
 	"QST-7440122-Ưu Tiên"
 ],
 shape: (10,)
 Series: '' [str]
 [
 	"TCT-7340120_CLC-TUYỂN THẲNG"
 	"TCT-7340121-TUYỂN THẲNG"
 	"TCT-7340302-TUYỂN THẲNG"
 	"TCT-7340201_CLC-TUYỂN THẲNG"
 	"TCT-7340301-TUYỂN THẲNG"
 	"TCT-7340101-TUYỂN THẲNG"
 	"TCT-7340201-TUYỂN THẲNG"
 	"TCT-7340101_CLC-TUYỂN THẲNG"
 	"TCT-7340115-TUYỂN THẲNG"
 	"TCT-7340120-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (8,)
 Series: '' [str]
 [
 	"HIU-7720601-TUYỂN THẲNG"
 	"HIU-7720302-TUYỂN THẲNG"
 	"HIU-7720603-TUYỂN THẲNG"
 	"HIU-7720115-TUYỂN THẲNG"
 	"HIU-7720701-TUYỂN THẲNG"
 	"HIU-7720401-TUYỂN THẲNG"
 	"HIU-7720301-TUYỂN THẲNG"
 	"HIU-7720201-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 shape: (3,)
 Series: '' [str]
 [
 	"USLA2-7760101-TUYỂN THẲNG"
 	"MBS-7760101-TUYỂN THẲNG"
 	"QSX-7760101-Ưu Tiên"
 ],
 shape: (2,)
 Series: '' [str]
 [
 	"DKB-7480103-TUYỂN THẲNG"
 	"DKB-7480201-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 shape: (35,)
 Series: '' [str]
 [
 	"KTS-7580102-TUYỂN THẲNG"
 	"MBS-7580302-TUYỂN THẲNG"
 	"GTS-7580201-TUYỂN THẲNG"
 	"KTS-7580105-TUYỂN THẲNG"
 	"KTS-7580210-TUYỂN THẲNG"
 	…
 	"QSQ-7580201_DK-Ưu Tiên"
 	"IUH-7580302-TUYỂN THẲNG"
 	"KTS-7580302-TUYỂN THẲNG"
 	"QSX-7580112-Ưu Tiên"
 	"KTS-7580201_CLC-TUYỂN THẲNG"
 ],
 shape: (1,)
 Series: '' [str]
 [
 	"QSA-7640101-TUYỂN THẲNG"
 ],
 [],
 shape: (33,)
 Series: '' [str]
 [
 	"SPS-7140211-Ưu Tiên"
 	"SPS-7140206_LA-Ưu Tiên"
 	"SPS-7140210-Ưu Tiên"
 	"SPS-7140213-Ưu Tiên"
 	"SPS-7140234-Ưu Tiên"
 	…
 	"SPS-7140201-Ưu Tiên"
 	"SPS-7140201_LA-Ưu Tiên"
 	"SPS-7140231-Ưu Tiên"
 	"QSX-7140114-Ưu Tiên"
 	"SGD-7140221-Ưu Tiên"
 ],
 [],
 [],
 shape: (3,)
 Series: '' [str]
 [
 	"QSA-7220201-TUYỂN THẲNG"
 	"QSA-7229030-TUYỂN THẲNG"
 	"QSA-7229001-TUYỂN THẲNG"
 ],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"DKB-7220210-TUYỂN THẲNG"
 	"DKB-7220201-TUYỂN THẲNG"
 ],
 shape: (3,)
 Series: '' [str]
 [
 	"QSA-7229030-TUYỂN THẲNG"
 	"QSA-7229001-TUYỂN THẲNG"
 	"QSA-7220201-TUYỂN THẲNG"
 ],
 shape: (23,)
 Series: '' [str]
 [
 	"MBS-7310620-TUYỂN THẲNG"
 	"QSX-7310614-Ưu Tiên"
 	"QSX-7310403-Ưu Tiên"
 	"USLA2-7310401-TUYỂN THẲNG"
 	"QSX-7310630-Ưu Tiên"
 	…
 	"QSX-7310613-Ưu Tiên"
 	"QSX-7310302-Ưu Tiên"
 	"USLA2-7310101-TUYỂN THẲNG"
 	"DTT-N7310630-Ưu Tiên"
 	"QSX-7310608-Ưu Tiên"
 ],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"PVU-7480101-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"QSA-7480103-TUYỂN THẲNG"
 	"QSA-7480201-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"DBD-7720203-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"TDM-7850101-TUYỂN THẲNG"
 	"TDM-7850103-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 shape: (3,)
 Series: '' [str]
 [
 	"TCT-7320104-TUYỂN THẲNG"
 	"TCT-7320101-TUYỂN THẲNG"
 	"TCT-7320201-TUYỂN THẲNG"
 ],
 shape: (45,)
 Series: '' [str]
 [
 	"QSQ-7220201_WE2-Ưu Tiên"
 	"HHK-7220201-TUYỂN THẲNG"
 	"QSX-7220204-Ưu Tiên"
 	"QSX-7229040-Ưu Tiên"
 	"NHS-7220201-TUYỂN THẲNG"
 	…
 	"UEF-7220210-TUYỂN THẲNG"
 	"QSX-7220204_CLC-Ưu Tiên"
 	"SPS-7220209-Ưu Tiên"
 	"QSX-7220208-Ưu Tiên"
 	"MBS-7220209-TUYỂN THẲNG"
 ],
 [],
 shape: (133,)
 Series: '' [str]
 [
 	"SGD-7340302-Ưu Tiên"
 	"UEF-7340101-TUYỂN THẲNG"
 	"DCT-7340101-TUYỂN THẲNG"
 	"USLA2-7340207-TUYỂN THẲNG"
 	"QSQ-7340101_WE4-Ưu Tiên"
 	…
 	"IUH-7340301-TUYỂN THẲNG"
 	"IUH-7340115-TUYỂN THẲNG"
 	"UEF-7340302-TUYỂN THẲNG"
 	"DTT-K7340120L-Ưu Tiên"
 	"MBS-7340101C-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"QSA-7510401-TUYỂN THẲNG"
 	"QSA-7510406-TUYỂN THẲNG"
 ],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"TCT-7380107-TUYỂN THẲNG"
 	"TCT-7380101-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"TDM-7460101-TUYỂN THẲNG"
 ],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"SPS-7420203-Ưu Tiên"
 ],
 shape: (9,)
 Series: '' [str]
 [
 	"TDM-7340201-TUYỂN THẲNG"
 	"TDM-7340302-TUYỂN THẲNG"
 	"TDM-7340101-TUYỂN THẲNG"
 	"DBD-7340101-TUYỂN THẲNG"
 	"TDM-7340115-TUYỂN THẲNG"
 	"TDM-7340122-TUYỂN THẲNG"
 	"DBD-7340301-TUYỂN THẲNG"
 	"DBD-7340201-TUYỂN THẲNG"
 	"TDM-7340301-TUYỂN THẲNG"
 ],
 shape: (10,)
 Series: '' [str]
 [
 	"TCT-7340201-TUYỂN THẲNG"
 	"TCT-7340120-TUYỂN THẲNG"
 	"TCT-7340201_CLC-TUYỂN THẲNG"
 	"TCT-7340301-TUYỂN THẲNG"
 	"TCT-7340115-TUYỂN THẲNG"
 	"TCT-7340302-TUYỂN THẲNG"
 	"TCT-7340120_CLC-TUYỂN THẲNG"
 	"TCT-7340121-TUYỂN THẲNG"
 	"TCT-7340101_CLC-TUYỂN THẲNG"
 	"TCT-7340101-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 shape: (7,)
 Series: '' [str]
 [
 	"TDM-7510601-TUYỂN THẲNG"
 	"DBD-7510605-TUYỂN THẲNG"
 	"DBD-7510102-TUYỂN THẲNG"
 	"DBD-7510301-TUYỂN THẲNG"
 	"TDM-7510205-TUYỂN THẲNG"
 	"TDM-7510605-TUYỂN THẲNG"
 	"DBD-7510205-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (8,)
 Series: '' [str]
 [
 	"UTC2-7840101-TUYỂN THẲNG"
 	"HHK-7840102-TUYỂN THẲNG"
 	"HHK-7840104K-TUYỂN THẲNG"
 	"HHK-7840102E-TUYỂN THẲNG"
 	"HHK-7840104L-TUYỂN THẲNG"
 	"HHK-7840104E-TUYỂN THẲNG"
 	"GTS-7840101-TUYỂN THẲNG"
 	"SPK-7840110V-Ưu Tiên"
 ],
 shape: (4,)
 Series: '' [str]
 [
 	"USLA2-7760101-TUYỂN THẲNG"
 	"MBS-7760101-TUYỂN THẲNG"
 	"QSX-7760101-Ưu Tiên"
 	"SPS-7760101-Ưu Tiên"
 ],
 [],
 [],
 [],
 shape: (54,)
 Series: '' [str]
 [
 	"KTS-7580105_CLC-TUYỂN THẲNG"
 	"KTS-7580101-TUYỂN THẲNG"
 	"UTC2-7580201-TUYỂN THẲNG"
 	"MTU-7580106-Ưu Tiên"
 	"TLU2-TLS114-TUYỂN THẲNG"
 	…
 	"QSB-315-Ưu Tiên"
 	"TLU2-TLS404-TUYỂN THẲNG"
 	"MTU-7580213-Ưu Tiên"
 	"MBS-7580302-TUYỂN THẲNG"
 	"QSB-147-Ưu Tiên"
 ],
 shape: (1,)
 Series: '' [str]
 [
 	"QSA-7640101-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (3,)
 Series: '' [str]
 [
 	"QSA-7220201-TUYỂN THẲNG"
 	"QSA-7229001-TUYỂN THẲNG"
 	"QSA-7229030-TUYỂN THẲNG"
 ],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"DKB-7220210-TUYỂN THẲNG"
 	"DKB-7220201-TUYỂN THẲNG"
 ],
 shape: (32,)
 Series: '' [str]
 [
 	"USLA2-7310401-TUYỂN THẲNG"
 	"SGD-7310501-Ưu Tiên"
 	"QSX-7310614-Ưu Tiên"
 	"QSX-7310630-Ưu Tiên"
 	"DTT-N7310630-Ưu Tiên"
 	…
 	"USLA2-7310101-TUYỂN THẲNG"
 	"SGD-7310601-Ưu Tiên"
 	"HCH-7310205-TUYỂN THẲNG"
 	"SPS-7310630-Ưu Tiên"
 	"QSX-7310501-Ưu Tiên"
 ],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"PVU-7480101-TUYỂN THẲNG"
 ],
 shape: (2,)
 Series: '' [str]
 [
 	"QSA-7480103-TUYỂN THẲNG"
 	"QSA-7480201-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"DBD-7720203-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (51,)
 Series: '' [str]
 [
 	"UEF-7220201-TUYỂN THẲNG"
 	"QSQ-7220201_WE3-Ưu Tiên"
 	"DCT-7220201-TUYỂN THẲNG"
 	"SGD-7220201CLC-Ưu Tiên"
 	"SGD-7220201-Ưu Tiên"
 	…
 	"USLA2-7220201-TUYỂN THẲNG"
 	"SPS-7220202-Ưu Tiên"
 	"SGD-7229010-Ưu Tiên"
 	"SPK-7220201V-Ưu Tiên"
 	"QSX-7220205-Ưu Tiên"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"QSA-7510406-TUYỂN THẲNG"
 	"QSA-7510401-TUYỂN THẲNG"
 ],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"SPS-7420203-Ưu Tiên"
 ],
 [],
 shape: (9,)
 Series: '' [str]
 [
 	"TDM-7340101-TUYỂN THẲNG"
 	"TDM-7340115-TUYỂN THẲNG"
 	"TDM-7340301-TUYỂN THẲNG"
 	"TDM-7340122-TUYỂN THẲNG"
 	"DBD-7340201-TUYỂN THẲNG"
 	"TDM-7340302-TUYỂN THẲNG"
 	"TDM-7340201-TUYỂN THẲNG"
 	"DBD-7340301-TUYỂN THẲNG"
 	"DBD-7340101-TUYỂN THẲNG"
 ],
 shape: (10,)
 Series: '' [str]
 [
 	"TCT-7340201-TUYỂN THẲNG"
 	"TCT-7340302-TUYỂN THẲNG"
 	"TCT-7340120-TUYỂN THẲNG"
 	"TCT-7340101-TUYỂN THẲNG"
 	"TCT-7340120_CLC-TUYỂN THẲNG"
 	"TCT-7340115-TUYỂN THẲNG"
 	"TCT-7340121-TUYỂN THẲNG"
 	"TCT-7340101_CLC-TUYỂN THẲNG"
 	"TCT-7340201_CLC-TUYỂN THẲNG"
 	"TCT-7340301-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 shape: (7,)
 Series: '' [str]
 [
 	"DBD-7510102-TUYỂN THẲNG"
 	"TDM-7510605-TUYỂN THẲNG"
 	"DBD-7510205-TUYỂN THẲNG"
 	"TDM-7510601-TUYỂN THẲNG"
 	"DBD-7510605-TUYỂN THẲNG"
 	"TDM-7510205-TUYỂN THẲNG"
 	"DBD-7510301-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 shape: (8,)
 Series: '' [str]
 [
 	"HIU-7720401-TUYỂN THẲNG"
 	"HIU-7720201-TUYỂN THẲNG"
 	"HIU-7720701-TUYỂN THẲNG"
 	"HIU-7720302-TUYỂN THẲNG"
 	"HIU-7720301-TUYỂN THẲNG"
 	"HIU-7720601-TUYỂN THẲNG"
 	"HIU-7720115-TUYỂN THẲNG"
 	"HIU-7720603-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 shape: (8,)
 Series: '' [str]
 [
 	"SPK-7840110V-Ưu Tiên"
 	"HHK-7840104K-TUYỂN THẲNG"
 	"HHK-7840104L-TUYỂN THẲNG"
 	"HHK-7840102E-TUYỂN THẲNG"
 	"UTC2-7840101-TUYỂN THẲNG"
 	"HHK-7840102-TUYỂN THẲNG"
 	"HHK-7840104E-TUYỂN THẲNG"
 	"GTS-7840101-TUYỂN THẲNG"
 ],
 [],
 shape: (50,)
 Series: '' [str]
 [
 	"SPS-7140233-Ưu Tiên"
 	"SPS-7140206-Ưu Tiên"
 	"SPS-7140208-Ưu Tiên"
 	"SPS-7140114-Ưu Tiên"
 	"SGD-7140219-Ưu Tiên"
 	…
 	"SPS-7140206_LA-Ưu Tiên"
 	"SPS-7140101-Ưu Tiên"
 	"SGD-7140217-Ưu Tiên"
 	"SGD-7140205-Ưu Tiên"
 	"SPS-7140217-Ưu Tiên"
 ],
 [],
 shape: (3,)
 Series: '' [str]
 [
 	"QSA-7220201-TUYỂN THẲNG"
 	"QSA-7229030-TUYỂN THẲNG"
 	"QSA-7229001-TUYỂN THẲNG"
 ],
 shape: (2,)
 Series: '' [str]
 [
 	"DKB-7220210-TUYỂN THẲNG"
 	"DKB-7220201-TUYỂN THẲNG"
 ],
 shape: (31,)
 Series: '' [str]
 [
 	"SGD-7310501-Ưu Tiên"
 	"USLA2-7310101-TUYỂN THẲNG"
 	"QSX-7310630-Ưu Tiên"
 	"SPS-7310630-Ưu Tiên"
 	"QSX-7310613-Ưu Tiên"
 	…
 	"USLA2-7310401-TUYỂN THẲNG"
 	"QSX-7310302-Ưu Tiên"
 	"SGD-7310630-Ưu Tiên"
 	"SPS-7310403-Ưu Tiên"
 	"QSX-73106a1-Ưu Tiên"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (51,)
 Series: '' [str]
 [
 	"SPS-7220210-Ưu Tiên"
 	"QSX-7220206-Ưu Tiên"
 	"QSX-7229030-Ưu Tiên"
 	"MBS-7220204-TUYỂN THẲNG"
 	"QSX-7220205CLC-Ưu Tiên"
 	…
 	"QSQ-7220201-Ưu Tiên"
 	"USLA2-7220201-TUYỂN THẲNG"
 	"HSU-7220204-TUYỂN THẲNG"
 	"UEF-7220201-TUYỂN THẲNG"
 	"MBS-7220204C-TUYỂN THẲNG"
 ],
 [],
 shape: (151,)
 Series: '' [str]
 [
 	"SGD-7340301-Ưu Tiên"
 	"HCH-7340406-TUYỂN THẲNG"
 	"NHS-7340101-TUYỂN THẲNG"
 	"HHK-7340120-TUYỂN THẲNG"
 	"QSC-7340122-Ưu Tiên"
 	…
 	"NHS-7340115-TUYỂN THẲNG"
 	"DCT-7340120-TUYỂN THẲNG"
 	"DTT-N7340301-Ưu Tiên"
 	"QSQ-7340101-Ưu Tiên"
 	"NHS-7340120-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (9,)
 Series: '' [str]
 [
 	"DBD-7340301-TUYỂN THẲNG"
 	"TDM-7340115-TUYỂN THẲNG"
 	"TDM-7340122-TUYỂN THẲNG"
 	"TDM-7340302-TUYỂN THẲNG"
 	"DBD-7340101-TUYỂN THẲNG"
 	"TDM-7340201-TUYỂN THẲNG"
 	"DBD-7340201-TUYỂN THẲNG"
 	"TDM-7340301-TUYỂN THẲNG"
 	"TDM-7340101-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 shape: (71,)
 Series: '' [str]
 [
 	"QSB-140-Ưu Tiên"
 	"UTC2-7520116-TUYỂN THẲNG"
 	"QSB-145-Ưu Tiên"
 	"UTC2-7520114-TUYỂN THẲNG"
 	"QSB-345-Ưu Tiên"
 	…
 	"QSB-242-Ưu Tiên"
 	"GTS-7520116-TUYỂN THẲNG"
 	"QSB-237-Ưu Tiên"
 	"QSC-752020a1-Ưu Tiên"
 	"QSQ-7520212-Ưu Tiên"
 ],
 [],
 [],
 [],
 [],
 shape: (7,)
 Series: '' [str]
 [
 	"TDM-7510605-TUYỂN THẲNG"
 	"DBD-7510301-TUYỂN THẲNG"
 	"DBD-7510605-TUYỂN THẲNG"
 	"TDM-7510601-TUYỂN THẲNG"
 	"DBD-7510205-TUYỂN THẲNG"
 	"TDM-7510205-TUYỂN THẲNG"
 	"DBD-7510102-TUYỂN THẲNG"
 ],
 shape: (2,)
 Series: '' [str]
 [
 	"TCT-7320101-TUYỂN THẲNG"
 	"TCT-7320201-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (14,)
 Series: '' [str]
 [
 	"SGD-7440301-Ưu Tiên"
 	"QST-7440112_DKD-Ưu Tiên"
 	"SPS-7440112-Ưu Tiên"
 	"QST-7440228-Ưu Tiên"
 	"QSQ-7440112-Ưu Tiên"
 	…
 	"QST-7440201_NN-Ưu Tiên"
 	"QST-7440102_NN-Ưu Tiên"
 	"SPS-7440102-Ưu Tiên"
 	"QST-7440301_DKD-Ưu Tiên"
 	"QST-7440112-Ưu Tiên"
 ],
 shape: (10,)
 Series: '' [str]
 [
 	"TCT-7340115-TUYỂN THẲNG"
 	"TCT-7340302-TUYỂN THẲNG"
 	"TCT-7340120-TUYỂN THẲNG"
 	"TCT-7340201-TUYỂN THẲNG"
 	"TCT-7340120_CLC-TUYỂN THẲNG"
 	"TCT-7340201_CLC-TUYỂN THẲNG"
 	"TCT-7340121-TUYỂN THẲNG"
 	"TCT-7340101-TUYỂN THẲNG"
 	"TCT-7340301-TUYỂN THẲNG"
 	"TCT-7340101_CLC-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 shape: (8,)
 Series: '' [str]
 [
 	"HHK-7840104L-TUYỂN THẲNG"
 	"HHK-7840102E-TUYỂN THẲNG"
 	"UTC2-7840101-TUYỂN THẲNG"
 	"SPK-7840110V-Ưu Tiên"
 	"HHK-7840104E-TUYỂN THẲNG"
 	"GTS-7840101-TUYỂN THẲNG"
 	"HHK-7840102-TUYỂN THẲNG"
 	"HHK-7840104K-TUYỂN THẲNG"
 ],
 [],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"QSA-7640101-TUYỂN THẲNG"
 ],
 [],
 shape: (50,)
 Series: '' [str]
 [
 	"SPS-7140211-Ưu Tiên"
 	"SPS-7140217_LA-Ưu Tiên"
 	"SPS-7140212-Ưu Tiên"
 	"SPS-7140209-Ưu Tiên"
 	"SPS-7140218-Ưu Tiên"
 	…
 	"SPS-7140246-Ưu Tiên"
 	"QSX-7140114-Ưu Tiên"
 	"SGD-7140247-Ưu Tiên"
 	"SGD-7140222-Ưu Tiên"
 	"SPS-7140206-Ưu Tiên"
 ],
 [],
 [],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"PVU-7480101-TUYỂN THẲNG"
 ],
 shape: (2,)
 Series: '' [str]
 [
 	"QSA-7480103-TUYỂN THẲNG"
 	"QSA-7480201-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 shape: (1,)
 Series: '' [str]
 [
 	"DBD-7720203-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"TDM-7850101-TUYỂN THẲNG"
 	"TDM-7850103-TUYỂN THẲNG"
 ],
 [],
 [],
 [],
 [],
 [],
 [],
 shape: (2,)
 Series: '' [str]
 [
 	"QSA-7510401-TUYỂN THẲNG"
 	"QSA-7510406-TUYỂN THẲNG"
 ],
 shape: (2,)
 Series: '' [str]
 [
 	"TCT-7380101-TUYỂN THẲNG"
 	"TCT-7380107-TUYỂN THẲNG"
 ]]

In [ ]:
# def get_pred_labels(probs):
#     if probs is None:  # chưa dự đoán
#         return []
#     return [k for k, v in probs.items()]

In [105]:
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.metrics import f1_score, precision_score, recall_score, hamming_loss

# y_true = [lbl if lbl is not None else [] for lbl in test_with_label['label']]
# y_pred = [get_pred_labels(p) for p in pred_df['probs_filtered']]


mlb = MultiLabelBinarizer()
y_true_bin = mlb.fit_transform(y_true)
y_pred_bin = mlb.transform(y_pred)

f1_micro = f1_score(y_true_bin, y_pred_bin, average='micro')
f1_macro = f1_score(y_true_bin, y_pred_bin, average='macro')
precision_micro = precision_score(y_true_bin, y_pred_bin, average='micro')
recall_micro = recall_score(y_true_bin, y_pred_bin, average='micro')
hamming = hamming_loss(y_true_bin, y_pred_bin)

print("F1 micro:", f1_micro)
print("F1 macro:", f1_macro)
print("Precision micro:", precision_micro)
print("Recall micro:", recall_micro)
print("Hamming loss:", hamming)

F1 micro: 0.9117408906882591
F1 macro: 0.9204026325977545
Precision micro: 0.8377976190476191
Recall micro: 1.0
Hamming loss: 0.0017938843356044897

/opt/miniconda3/envs/eda/lib/python3.11/site-packages/sklearn/preprocessing/_label.py:909: UserWarning: unknown class(es) ['DBD-7220201-TUYỂN THẲNG', 'DBD-7480201-TUYỂN THẲNG', 'DCT-7460108-TUYỂN THẲNG', 'DCT-7540101-TUYỂN THẲNG', 'DCT-7540105-TUYỂN THẲNG', 'DCT-7540106-TUYỂN THẲNG', 'DCT-7540204-TUYỂN THẲNG', 'DKB-7340101-TUYỂN THẲNG', 'DKB-7340115-TUYỂN THẲNG', 'DKB-7340122-TUYỂN THẲNG', 'DKB-7340201-TUYỂN THẲNG', 'DKB-7340301-TUYỂN THẲNG', 'DKB-7340406-TUYỂN THẲNG', 'DKB-7510205-TUYỂN THẲNG', 'DKB-7510301-TUYỂN THẲNG', 'DKB-7510605-TUYỂN THẲNG', 'FUV-7229010-TUYỂN THẲNG', 'FUV-7229030-TUYỂN THẲNG', 'FUV-8449001-TUYỂN THẲNG', 'HIU-7140114-TUYỂN THẲNG', 'HIU-7220201-TUYỂN THẲNG', 'HIU-7220204-TUYỂN THẲNG', 'HIU-7220209-TUYỂN THẲNG', 'HIU-7220210-TUYỂN THẲNG', 'HIU-7340101-TUYỂN THẲNG', 'HIU-7340114-TUYỂN THẲNG', 'HIU-7340122-TUYỂN THẲNG', 'HIU-7340201-TUYỂN THẲNG', 'HIU-7340301-TUYỂN THẲNG', 'HIU-7340412-TUYỂN THẲNG', 'HIU-7580101-TUYỂN THẲNG', 'IUH-7460108-TUYỂN THẲNG', 'IUH-7540101-TUYỂN THẲNG', 'IUH-7540101C-TUYỂN THẲNG', 'IUH-7540106-TUYỂN THẲNG', 'IUH-7540204-TUYỂN THẲNG', 'IUH-7720201-TUYỂN THẲNG', 'IUH-7720497-TUYỂN THẲNG', 'MBS-7460108-TUYỂN THẲNG', 'MBS-7540101-TUYỂN THẲNG', 'NHS-746108-TUYỂN THẲNG', 'QSA-7140201-TUYỂN THẲNG', 'QSA-7140202-TUYỂN THẲNG', 'QSA-7140205-TUYỂN THẲNG', 'QSA-7140209-TUYỂN THẲNG', 'QSA-7140211-TUYỂN THẲNG', 'QSA-7140212-TUYỂN THẲNG', 'QSA-7140213-TUYỂN THẲNG', 'QSA-7140217-TUYỂN THẲNG', 'QSA-7140218-TUYỂN THẲNG', 'QSA-7140219-TUYỂN THẲNG', 'QSA-7140231-TUYỂN THẲNG', 'QSA-7140247-TUYỂN THẲNG', 'QSA-7310106-TUYỂN THẲNG', 'QSA-7310630-TUYỂN THẲNG', 'QSA-7420201-TUYỂN THẲNG', 'QSB-112-Ưu Tiên', 'QSB-319-Ưu Tiên', 'QSC-7460108-Ưu Tiên', 'QSQ-7460108-Ưu Tiên', 'QSQ-7460112-Ưu Tiên', 'QSQ-7460201-Ưu Tiên', 'QST-7460101_NN-Ưu Tiên', 'QST-7460108-Ưu Tiên', 'QSY-7720101-TUYỂN THẲNG', 'QSY-7720115-TUYỂN THẲNG', 'QSY-7720201-TUYỂN THẲNG', 'QSY-7720301-TUYỂN THẲNG', 'QSY-7720501-TUYỂN THẲNG', 'SGD-7460108-Ưu Tiên', 'SGD-7460112-Ưu Tiên', 'SPK-7540101DD-Ưu Tiên', 'SPK-7540101V-Ưu Tiên', 'SPK-7540209V-Ưu Tiên', 'SPK-7549002V-Ưu Tiên', 'TCT-7310101-TUYỂN THẲNG', 'TCT-7310201-TUYỂN THẲNG', 'TCT-7310301-TUYỂN THẲNG', 'TCT-7420101-TUYỂN THẲNG', 'TCT-7420201-TUYỂN THẲNG', 'TCT-7420201_TT-TUYỂN THẲNG', 'TCT-7420203-TUYỂN THẲNG', 'TCT-7480101-TUYỂN THẲNG', 'TCT-7480102-TUYỂN THẲNG', 'TCT-7480103-TUYỂN THẲNG', 'TCT-7480103_CLC-TUYỂN THẲNG', 'TCT-7480104-TUYỂN THẲNG', 'TCT-7480104_CLC-TUYỂN THẲNG', 'TCT-7480106-TUYỂN THẲNG', 'TCT-7480201-TUYỂN THẲNG', 'TCT-7480201_CLC-TUYỂN THẲNG', 'TCT-7480202-TUYỂN THẲNG', 'TCT-7510401-TUYỂN THẲNG', 'TCT-7510401_CLC-TUYỂN THẲNG', 'TCT-7510601-TUYỂN THẲNG', 'TCT-7510605-TUYỂN THẲNG', 'TDM-7210201-TUYỂN THẲNG', 'TDM-7210403-TUYỂN THẲNG', 'TDM-7220201-TUYỂN THẲNG', 'TDM-7220204-TUYỂN THẲNG', 'TDM-7220210-TUYỂN THẲNG', 'TDM-7420201-TUYỂN THẲNG', 'TDM-7480103-TUYỂN THẲNG', 'TDM-7480201-TUYỂN THẲNG', 'TYS-7720101-Ưu Tiên', 'TYS-7720115-Ưu Tiên', 'TYS-7720201-Ưu Tiên', 'TYS-7720301-Ưu Tiên', 'TYS-7720302-Ưu Tiên', 'TYS-7720401-Ưu Tiên', 'TYS-7720501-Ưu Tiên', 'TYS-7720601-Ưu Tiên', 'TYS-7720602-Ưu Tiên', 'TYS-7720603-Ưu Tiên', 'TYS-7720699-Ưu Tiên', 'TYS-7720701-Ưu Tiên', 'UEF-7460108-TUYỂN THẲNG', 'VGU-7480101-TUYỂN THẲNG', 'YDS-7720101-TUYỂN THẲNG', 'YDS-7720110-TUYỂN THẲNG', 'YDS-7720115-TUYỂN THẲNG', 'YDS-7720201-TUYỂN THẲNG', 'YDS-7720203-TUYỂN THẲNG', 'YDS-7720301-TUYỂN THẲNG', 'YDS-7720302-TUYỂN THẲNG', 'YDS-7720401-TUYỂN THẲNG', 'YDS-7720501-TUYỂN THẲNG', 'YDS-7720502-TUYỂN THẲNG', 'YDS-7720601-TUYỂN THẲNG', 'YDS-7720602-TUYỂN THẲNG', 'YDS-7720603-TUYỂN THẲNG', 'YDS-7720701-TUYỂN THẲNG'] will be ignored
  warnings.warn(

In [24]:
df_test = out.reset_index(drop=True).assign(row_id=lambda d: d.index)

full_out = (
    df_test
    .merge(pred_df, on='row_id', how='left', suffixes=('', '_pred'))
)
print(full_out)

     cong_lap          tinh_tp    hoc_phi  nhom_nganh hsg_subject  ahld  \
0           1  TP. Hồ Chí Minh   20000000         742         Văn     0
1           0         Vũng Tàu  100000000         746  Tiếng Nhật     0
2           1       Bình Dương   40000000         734        Sinh     0
3           1          Cần Thơ  500000000         734         Văn     0
4           1         An Giang  100000000         776         Anh     0
..        ...              ...        ...         ...         ...   ...
242         1          Cần Thơ   10000000         784           0     0
243         0  TP. Hồ Chí Minh  200000000         746           0     0
244         0          Cần Thơ   80000000         748           0     0
245         1         An Giang   60000000         751           0     0
246         1          Cần Thơ   40000000         738           0     0

     dan_toc_thieu_so  haimuoi_huyen_ngheo_tnb  row_id  \
0                   0                        0       0
1                   0                        0       1
2                   0                        0       2
3                   0                        0       3
4                   0                        0       4
..                ...                      ...     ...
242                 0                        1     242
243                 0                        1     243
244                 0                        1     244
245                 0                        1     245
246                 0                        1     246

                      group        status                     pred  \
0    (TP. Hồ Chí Minh, 742)            ok  DCT-7420201-TUYỂN THẲNG
1           (Vũng Tàu, 746)  unseen_group                     None
2         (Bình Dương, 734)            ok  VGU-7340101-TUYỂN THẲNG
3            (Cần Thơ, 734)            ok  TCT-7340101-TUYỂN THẲNG
4           (An Giang, 776)  unseen_group                     None
..                      ...           ...                      ...
242          (Cần Thơ, 784)  unseen_group                     None
243  (TP. Hồ Chí Minh, 746)            ok  FUV-7460112-TUYỂN THẲNG
244          (Cần Thơ, 748)            ok  TCT-7480101-TUYỂN THẲNG
245         (An Giang, 751)            ok  QSA-7510401-TUYỂN THẲNG
246          (Cần Thơ, 738)            ok  TCT-7380101-TUYỂN THẲNG

                                                 probs
0    {'DCT-7420201-TUYỂN THẲNG': 0.0745626552284294...
1                                                 None
2    {'VGU-7340101-TUYỂN THẲNG': 0.0883176683658808...
3    {'TCT-7340101-TUYỂN THẲNG': 0.1, 'TCT-7340101_...
4                                                 None
..                                                 ...
242                                               None
243  {'FUV-7460112-TUYỂN THẲNG': 0.8743064616074306...
244  {'TCT-7480101-TUYỂN THẲNG': 0.1, 'TCT-7480102-...
245  {'QSA-7510401-TUYỂN THẲNG': 0.5, 'QSA-7510406-...
246  {'TCT-7380101-TUYỂN THẲNG': 0.5, 'TCT-7380107-...

[247 rows x 13 columns]

In [110]:
results = full_out[full_out["hoc_phi_ceiled"]<=20000000]

In [111]:
results

,cong_lap,tinh_tp,hoc_phi,nhom_nganh,hsg_subject,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,hoc_phi_ceiled,fee_bin_idx,is_free,row_id,group,status,pred,probs
0,0,Vũng Tàu,10000000,764,Tin,0,0,0,10000000,1,0,0,"(0, Vũng Tàu, 764)",unseen_group,None,None
2,1,TP. Hồ Chí Minh,0,744,Tiếng Pháp,0,0,0,0,0,1,2,"(1, TP. Hồ Chí Minh, 744)",ok,QST-7440122-Ưu Tiên,"{'QST-7440122-Ưu Tiên': 0.08915140642813726, '..."
3,1,Vũng Tàu,20000000,732,Tiếng Pháp,0,0,0,20000000,2,0,3,"(1, Vũng Tàu, 732)",unseen_group,None,None
8,1,Bình Dương,10000000,746,Tin,0,0,0,10000000,1,0,8,"(1, Bình Dương, 746)",single_class,TDM-7460101-TUYỂN THẲNG,{'TDM-7460101-TUYỂN THẲNG': 1.0}
9,1,Cần Thơ,0,772,Lý,0,0,0,0,0,1,9,"(1, Cần Thơ, 772)",single_class,TCT-7720203-TUYỂN THẲNG,{'TCT-7720203-TUYỂN THẲNG': 1.0}
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
243,1,Bình Dương,0,722,0,0,0,1,0,0,1,243,"(1, Bình Dương, 722)",ok,DBD-7220201-TUYỂN THẲNG,"{'DBD-7220201-TUYỂN THẲNG': 0.25, 'TDM-7220201..."
246,0,Vũng Tàu,0,764,0,0,0,1,0,0,1,246,"(0, Vũng Tàu, 764)",unseen_group,None,None
248,1,TP. Hồ Chí Minh,20000000,738,0,0,0,1,20000000,2,0,248,"(1, TP. Hồ Chí Minh, 738)",ok,MBS-7380107C-TUYỂN THẲNG,{'MBS-7380107C-TUYỂN THẲNG': 0.053534624424316...
249,1,Cần Thơ,0,752,0,0,0,1,0,0,1,249,"(1, Cần Thơ, 752)",ok,TCT-7520103-TUYỂN THẲNG,{'TCT-7520103-TUYỂN THẲNG': 0.0833333333333333...
250,0,Bình Dương,0,772,0,0,0,1,0,0,1,250,"(0, Bình Dương, 772)",unseen_group,None,None

In [88]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40915 entries, 0 to 40914
Data columns (total 12 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Công lập (1/0)           40915 non-null  int64
 1   Tỉnh/TP                  40915 non-null  object
 2   Tổ hợp môn               3393 non-null   object
 3   Học phí                  40553 non-null  float64
 4   hsg_1                    40915 non-null  object
 5   hsg_2                    40915 non-null  object
 6   hsg_3                    40915 non-null  object
 7   ahld                     40915 non-null  int64
 8   dan_toc_thieu_so         40915 non-null  int64
 9   haimuoi_huyen_ngheo_tnb  40915 non-null  int64
 10  truong-nganh-ptxt        40915 non-null  object
 11  nhom_nganh               40915 non-null  int64
dtypes: float64(1), int64(5), object(6)
memory usage: 3.7+ MB

In [87]:
df1[(df1["Công lập (1/0)"] == 1) & (df1["Tỉnh/TP"] == "TP. Hồ Chí Minh") & (df1["Học phí"] == 0.0) & (df1["nhom_nganh"] == 754) & (df1["hsg_1"] == "Văn") ]

Empty DataFrame
Columns: [Công lập (1/0), Tỉnh/TP, Tổ hợp môn, Học phí, hsg_1, hsg_2, hsg_3, ahld, dan_toc_thieu_so, haimuoi_huyen_ngheo_tnb, truong-nganh-ptxt, nhom_nganh]
Index: []

In [108]:
import joblib, sklearn, sys
from datetime import datetime

bundle = {
    "models": models,
    "encoders": encoders,
    "label_encoders": label_encoders,
    "class_lists": class_lists,
    "meta": {
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "sklearn_version": sklearn.__version__,
        "python_version": sys.version.split()[0],
        "group_cols": group_cols,
        "ohe_cols": ohe_cols,
        "target_col": target_col,
    },
}

save_path = "../../models/l1_model_group_wise.joblib"
joblib.dump(bundle, save_path, compress=3)
save_path

'../../models/l1_model_group_wise.joblib'

In [1]:
import pandas as pd


df = pd.read_excel('../../data/train_l1.xlsx')

df[(df["Công lập (1/0)"]==0) & (df["Tỉnh/TP"]=="TP. Hồ Chí Minh") & (df["nhom_nganh"]==752)]

,Công lập (1/0),Tỉnh/TP,Tổ hợp môn,Học phí,hsg_1,hsg_2,hsg_3,ahld,dan_toc_thieu_so,haimuoi_huyen_ngheo_tnb,truong-nganh-ptxt,nhom_nganh
2238,0,TP. Hồ Chí Minh,NaN,467600000.0,Anh,0,0,0,0,0,FUV-7520212-TUYỂN THẲNG,752
14693,0,TP. Hồ Chí Minh,NaN,467600000.0,0,Anh,0,0,0,0,FUV-7520212-TUYỂN THẲNG,752
27144,0,TP. Hồ Chí Minh,NaN,467600000.0,0,0,Anh,0,0,0,FUV-7520212-TUYỂN THẲNG,752
37557,0,TP. Hồ Chí Minh,NaN,467600000.0,0,0,0,1,0,0,FUV-7520212-TUYỂN THẲNG,752
38748,0,TP. Hồ Chí Minh,NaN,467600000.0,0,0,0,0,1,0,FUV-7520212-TUYỂN THẲNG,752
39939,0,TP. Hồ Chí Minh,NaN,467600000.0,0,0,0,0,0,1,FUV-7520212-TUYỂN THẲNG,752